import {useEffect,useState} from 'react';
import type {Mission,ArtifactOperation,ArtifactPlan,WorkspaceArtifact} from '@mission/domain';
import {Button,Badge} from '@mission/ui';
import {CommunicationComposer,CommunicationReview} from './CommunicationReview';
import {api,post} from '../api';
interface PlanRecord {id:string;data:ArtifactPlan;review:{digest:string;expiresAt:string}}
interface OperationRecord {id:string;data:{state:string;code?:string;providerId?:string}}
interface ArtifactRecord {id:string;data:WorkspaceArtifact}
export function ArtifactWorkspace({mission}:{mission:Mission}){
 const [operations,setOperations]=useState<OperationRecord[]>([]);const [plans,setPlans]=useState<PlanRecord[]>([]);const [artifacts,setArtifacts]=useState<ArtifactRecord[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const [selected,setSelected]=useState(['docs','sheets','slides','mail','chat','calendar']);
 const [nativeDraft,setNativeDraft]=useState(false);const [notesIndex,setNotesIndex]=useState('');const [meetingStart,setMeetingStart]=useState('2026-09-14T15:00:00.000Z');const [meetingEnd,setMeetingEnd]=useState('2026-09-14T15:30:00.000Z');const [timezone,setTimezone]=useState('Etc/UTC');
 const [draft,setDraft]=useState('');const [targetApp,setTargetApp]=useState('docs');const [targetId,setTargetId]=useState('');const [targets,setTargets]=useState<WorkspaceArtifact[]>([]);const [replace,setReplace]=useState(false);
 const [capabilities,setCapabilities]=useState<{mode:string;consequentialReady:boolean;capabilities:Array<{app:string;write:string;blocker:string}>}|null>(null);
 const refresh=async()=>{const r=await api<{plans:PlanRecord[];artifacts:ArtifactRecord[];operations:OperationRecord[]}>(`/api/missions/${mission.id}/artifact-plans`);setPlans(r.plans);setArtifacts(r.artifacts);setOperations(r.operations);};
 useEffect(()=>{let active=true;setPlans([]);setArtifacts([]);setOperations([]);setTargets([]);setDraft('');setReplace(false);setNativeDraft(false);setTargetId('');setMessage('');void api<{plans:PlanRecord[];artifacts:ArtifactRecord[];operations:OperationRecord[]}>(`/api/missions/${mission.id}/artifact-plans`).then(r=>{if(active){setPlans(r.plans);setArtifacts(r.artifacts);setOperations(r.operations);}}).catch(e=>{if(active)setMessage(e.message);});void api<NonNullable<typeof capabilities>>('/api/workspace/capabilities').then(r=>{if(active)setCapabilities(r);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[mission.id]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await fn();await refresh();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const create=()=>act(async()=>{
  const content=draft||mission.evidence.map(e=>`Source ${e.id} · ${e.capturedAt}\n${e.excerpt}`).join('\n\n');
  const facts=draft?[{id:'manual-review-facts',text:draft,at:mission.updatedAt}]:mission.evidence.map(e=>({id:e.id,text:e.excerpt,at:e.capturedAt}));
  const operations=selected.map((app,index):ArtifactOperation=>{
   const existingTarget=targets.find(a=>a.app===app);const existing=existingTarget?{id:existingTarget.id,data:existingTarget}:artifacts.find(a=>a.data.app===app && a.data.state==='verified');
   const prepare=['mail','chat','calendar'].includes(app)&&!(app==='mail'&&nativeDraft);
   return {id:`output-${index}`,app:app as ArtifactOperation['app'],action:prepare?'prepare':existing?'update':'create',title:`Launch review · ${app}`,content,sourceSnapshotIds:mission.evidence.map(e=>e.id),dependsOn:[],audience:[],replacementApproved:replace&&app==='docs',verification:'read_back',...(existing&&!prepare?{targetId:existing.id,expectedFingerprint:existing.data.fingerprint,beforeContent:existing.data.content}:{}),...(app==='sheets'?{cells:facts.flatMap((fact,row)=>[{row,rowKey:fact.id,column:'claim',value:fact.text},{row,rowKey:fact.id,column:'source',value:fact.id},{row,rowKey:fact.id,column:'capturedAt',value:fact.at}])}:{}),...(app==='slides'&&notesIndex.trim()?{slideIndex:Number(notesIndex)}:{}),...(app==='calendar'?{startAt:meetingStart,endAt:meetingEnd,timezone}:{})};
  });
  await post(`/api/missions/${mission.id}/artifact-plans`,{outcome:'Prepare the launch review from selected saved evidence.',operations});setMessage('Plan saved. Inspect each output before approving.');
 });
 return <section className="card" aria-label="Connected artifacts"><div className="card-header"><h2>Connected artifacts</h2><Badge>{capabilities?.mode??'Loading'}</Badge></div>
  <p>Build a review from saved mission evidence. Default mail, chat, and meeting outputs are local proposals; sending requires separate review. Existing fixture targets are updated on the next review.</p>
  {!mission.evidence.length&&<p role="status">Save selected browser context as evidence first, or enter a brief below.</p>}
  <details><summary>Select an existing workspace target</summary><label>Application<select value={targetApp} onChange={e=>setTargetApp(e.target.value)}>{['docs','sheets','slides','mail','chat','calendar','tasks'].map(app=><option key={app}>{app}</option>)}</select></label><label>Selected object ID<input value={targetId} onChange={e=>setTargetId(e.target.value)} placeholder="Exact provider object ID"/></label><Button disabled={busy||!targetId.trim()} onClick={()=>void act(async()=>{const a=await post<WorkspaceArtifact>(`/api/missions/${mission.id}/workspace/read`,{app:targetApp,id:targetId});setTargets(t=>[...t.filter(x=>x.app!==a.app),a]);setReplace(false);})}>Read selected target</Button>{targets.map(a=><article key={a.id}><h3>{a.title} · current content</h3><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{a.content}</pre><Button onClick={()=>setTargets(t=>t.filter(x=>x.id!==a.id))}>Remove target</Button></article>)}<label><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>I reviewed the entire current document and authorize proposing full replacement with the facts below.</label></details>
  <fieldset><legend>Outputs to include</legend>{['docs','sheets','slides','mail','chat','calendar'].map(app=><label key={app} style={{display:'inline-flex',gap:6,marginRight:12}}><input type="checkbox" checked={selected.includes(app)} onChange={e=>setSelected(s=>e.target.checked?[...s,app]:s.filter(a=>a!==app))}/>{app}</label>)}</fieldset>
  {capabilities?.mode==='live'&&<><label><input type="checkbox" checked={nativeDraft} onChange={e=>setNativeDraft(e.target.checked)}/>Save email as a native private draft after approval (never send)</label><label>Explicit slide notes update · zero-based slide index<input value={notesIndex} onChange={e=>setNotesIndex(e.target.value)} placeholder="Leave blank for rich presentation proposal" inputMode="numeric"/></label></>}
  {selected.includes('calendar')&&<details><summary>Meeting proposal timing · availability unverified</summary><label>Start (ISO with offset)<input value={meetingStart} onChange={e=>setMeetingStart(e.target.value)}/></label><label>End (ISO with offset)<input value={meetingEnd} onChange={e=>setMeetingEnd(e.target.value)}/></label><label>Timezone<input value={timezone} onChange={e=>setTimezone(e.target.value)}/></label></details>}
  <label>Normalized review facts<textarea aria-label="Normalized review facts" rows={4} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Leave empty to use saved mission evidence. Do not infer missing facts."/></label>
  <Button disabled={busy||!selected.length||(!mission.evidence.length&&!draft.trim())} onClick={create}>Prepare artifact plan</Button>
  <CommunicationComposer key={mission.id} mission={mission} onSaved={refresh}/>
  {message&&<p role="status">{message}</p>}
  {plans.map(({data:plan,review})=><details key={plan.id}><summary>{plan.outcome} · revision {plan.missionRevision}</summary><p>Review expires {review.expiresAt}</p>{plan.operations.map(op=><article key={op.id}><h3>{op.title} · {op.action}</h3><p>{op.targetId?`Target: ${op.targetId}`:'New output'} · {op.sourceSnapshotIds.length} cited sources</p>{op.beforeContent!==undefined&&<details open><summary>Before · reviewed target</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{op.beforeContent}</pre></details>}<details open><summary>{op.action==='update'?'After · proposed change':'Proposed content'}</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{op.cells?JSON.stringify(op.cells,null,2):op.content||'No content'}</pre></details>{op.app==='calendar'&&<p>{op.startAt} — {op.endAt} ({op.timezone}); proposed only, availability unknown.</p>}</article>)}{plan.operations.some(op=>op.action==='send'||op.action==='invite')?<CommunicationReview key={plan.id} plan={plan} mission={mission} ready={capabilities?.consequentialReady===true} busy={busy} onApprove={category=>act(async()=>{const r=await post<{results:Array<{state:string;code?:string}>}>(`/api/missions/${mission.id}/artifact-plans/${plan.id}/execute-consequential`,{approve:true,digest:review.digest,category,acknowledgeSourceSharing:true});setMessage(r.results.map(x=>`${x.state}${x.code?`: ${x.code}`:''}`).join('; '));})}/>:<Button disabled={busy||plan.missionRevision!==mission.revision} onClick={()=>void act(async()=>{const r=await post<{results:Array<{state:string;code?:string}>}>(`/api/missions/${mission.id}/artifact-plans/${plan.id}/execute`,{approve:true,digest:review.digest});setMessage(r.results.map(x=>`${x.state}${x.code?`: ${x.code}`:''}`).join('; '));})}>Approve these private outputs</Button>}</details>)}
  {artifacts.map(({data:a})=><details key={a.id}><summary>{a.title} · {a.state} · {a.mode}</summary><p>Provider ID: {a.id}<br/>Verified: {a.verifiedAt??'Not executed'}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{a.content}</pre></details>)}
  {operations.map(o=><details key={o.id}><summary>Operation · {o.data.state}</summary><p>{o.id}<br/>{o.data.code}<br/>Provider ID: {o.data.providerId??'None returned'}</p>{o.data.state==='outcome_unknown'&&o.data.providerId&&<Button disabled={busy} onClick={()=>void act(async()=>{const r=await post<{state:string}>(`/api/missions/${mission.id}/artifact-operations/${o.id}/reconcile`,{});setMessage(`Read-only reconciliation: ${r.state}`);})}>Inspect provider read-back</Button>}</details>)}
  <details><summary>Workspace capability limits</summary>{capabilities?.capabilities.map(c=><p key={c.app}><strong>{c.app}</strong>: {c.write}. {c.blocker}</p>)}</details>
 </section>;
}
