import {useState} from 'react';
import type {Mission} from '@mission/domain';
import {Button,Field,Notice} from '@mission/ui';
export function NewTaskCard({mission,onPropose,onCancel,busy,seed}:{mission:Mission;onPropose:(input:unknown)=>Promise<void>;onCancel:()=>void;busy:boolean;seed?:{title:string;description:string}|null}){
  const [title,setTitle]=useState(seed?.title||'');const [description,setDescription]=useState(seed?.description||'Owner-proposed task.');const [minutes,setMinutes]=useState('30');const [executor,setExecutor]=useState<'human'|'agent'>('human');const [dependencies,setDependencies]=useState<string[]>([]);const [criteria,setCriteria]=useState<string[]>([]);const [proof,setProof]=useState('');const [optional,setOptional]=useState(false);const [error,setError]=useState('');
  return <section className="capture-preview"><div className="section-heading"><div><h2>Propose a task</h2><p>Review the new task before creating a provider record.</p></div></div><form onSubmit={async e=>{e.preventDefault();setError('');try{await onPropose({title,description,remainingMinutes:minutes===''?null:Number(minutes),executor,dependencies,criterionIds:criteria,completionEvidence:proof,optional});onCancel();}catch(error){setError(error instanceof Error?error.message:'Could not propose task.');}}}>
    <Field label="Task title"><input required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Task description"><textarea maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)}/></Field><div className="two-fields"><Field label="Remaining effort (minutes)"><input type="number" min="0" placeholder="Unknown" value={minutes} onChange={e=>setMinutes(e.target.value)}/></Field><Field label="Executor"><select value={executor} onChange={e=>setExecutor(e.target.value as 'human'|'agent')}><option value="human">Human</option><option value="agent">Agent</option></select></Field></div><Field label="Completion evidence"><textarea required value={proof} maxLength={2000} onChange={e=>setProof(e.target.value)}/></Field>
    <fieldset><legend>Dependencies</legend>{mission.tasks.filter(t=>!t.deferred).map(t=><label className="check-label" key={t.id}><input type="checkbox" checked={dependencies.includes(t.id)} onChange={e=>setDependencies(e.target.checked?[...dependencies,t.id]:dependencies.filter(id=>id!==t.id))}/>{t.title}</label>)}</fieldset><fieldset><legend>Supports criteria</legend>{mission.criteria.map(c=><label className="check-label" key={c.id}><input type="checkbox" checked={criteria.includes(c.id)} onChange={e=>setCriteria(e.target.checked?[...criteria,c.id]:criteria.filter(id=>id!==c.id))}/>{c.title}</label>)}</fieldset><label className="check-label"><input type="checkbox" checked={optional} onChange={e=>setOptional(e.target.checked)}/>Optional work</label>{error&&<Notice tone="red">{error}</Notice>}<div className="actions"><Button type="submit" busy={busy}>Prepare task proposal</Button><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button></div>
  </form></section>;
}
