import {useState} from 'react';
import type {Mission,Proposal,ProposalOperation,Task} from '@mission/domain';
import {Badge,Button,Field,Notice} from '@mission/ui';
import {AlertCircle,ArrowRight,Check,Clock,Link2,Plus,User,Workflow} from 'lucide-react';
import {dateTime,formatTimestampsInText,localInput,readable,zonedInputToIso} from '../format';

export interface ProposalActions {approve:(proposal:Proposal)=>Promise<void>;reject:(proposal:Proposal)=>Promise<void>;edit:(proposal:Proposal,operations:ProposalOperation[])=>Promise<void>;refreshProposal:(proposal:Proposal)=>Promise<void>;busy?:boolean}
export function PlanReview({mission,proposal,...actions}:{mission:Mission;proposal:Proposal}&ProposalActions){return <ProposalReview mission={mission} proposal={proposal} {...actions}/>;}
export function MissingRequirementCard({mission,proposal,...actions}:{mission:Mission;proposal:Proposal}&ProposalActions){return <ProposalReview mission={mission} proposal={proposal} {...actions}/>;}
export function RecoveryPlanDiff({mission,proposal,...actions}:{mission:Mission;proposal:Proposal}&ProposalActions){return <ProposalReview mission={mission} proposal={proposal} {...actions}/>;}

function ProposalReview({mission,proposal,approve,reject,edit,refreshProposal,busy}: {mission:Mission;proposal:Proposal}&ProposalActions) {
  const [editing,setEditing]=useState(false);
  const [operations,setOperations]=useState(proposal.operations);
  const [error,setError]=useState('');
  const expired=new Date(proposal.expiresAt).getTime()<Date.now();
  const stale=proposal.state==='stale' || expired || proposal.baseRevision!==mission.revision;
  const pending=proposal.state==='pending';
  const allTasks=[...mission.tasks,...operations.flatMap(o=>o.type==='add_task'?[o.task]:[])];
  async function run(action:()=>Promise<void>){setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Could not apply this proposal.');}}
  function changeOperation(index:number,operation:ProposalOperation){setOperations(operations.map((o,i)=>i===index?operation:o));}
  function changeTask(index:number,patch:Partial<Task>){setOperations(operations.map((o,i)=>i===index&&o.type==='add_task'?{...o,task:{...o.task,...patch}}:o));}
  return <article className={`proposal-card proposal-card--${proposal.kind}`}>
    <div className="proposal-heading"><span className="proposal-symbol">{proposal.kind==='requirement'?<AlertCircle size={20}/>:<Workflow size={20}/>}</span><div><h3>{proposal.title}</h3><Badge tone={stale?'red':pending?'amber':'green'}>{stale?'Needs refresh':pending?'Pending review':readable(proposal.state)}</Badge></div></div>
    <div className="proposal-body"><p>{proposal.rationale}</p>
      {proposal.evidenceIds.map(id=>mission.evidence.find(e=>e.id===id)).filter(Boolean).map(e=><div className="source-excerpt" key={e!.id}><span className="small muted">Supporting excerpt{e!.fixture?' · fixture':''}</span><blockquote>{e!.excerpt}</blockquote>{e!.sourceUrl && <a href={e!.sourceUrl} target="_blank" rel="noreferrer">{e!.title}</a>}</div>)}
      <div className="change-list">{operations.map((operation,index)=><div className="change-row" key={index}>
        {operation.type==='add_task' && <><div className="change-label"><Plus size={14}/>Added task{operation.task.suggested && <span>Suggestion</span>}</div>{editing?<>
          <Field label="Task title"><input value={operation.task.title} onChange={e=>changeTask(index,{title:e.target.value})}/></Field>
          <div className="two-fields"><Field label="Effort in minutes"><input type="number" min="0" value={operation.task.remainingMinutes??''} placeholder="Unknown" onChange={e=>changeTask(index,{remainingMinutes:e.target.value===''?null:Number(e.target.value)})}/></Field><Field label="Executor"><select value={operation.task.executor} onChange={e=>changeTask(index,{executor:e.target.value as Task['executor']})}><option value="human">Human</option><option value="agent">Agent</option></select></Field></div>
          <Field label="Completion evidence"><textarea value={operation.task.completionEvidence} onChange={e=>changeTask(index,{completionEvidence:e.target.value})}/></Field>
          <fieldset><legend>Dependencies</legend>{allTasks.filter(t=>t.id!==operation.task.id).map(t=><label className="check-label" key={t.id}><input type="checkbox" checked={operation.task.dependencies.includes(t.id)} onChange={e=>changeTask(index,{dependencies:e.target.checked?[...operation.task.dependencies,t.id]:operation.task.dependencies.filter(id=>id!==t.id)})}/>{t.title}</label>)}</fieldset>
        </>:<><strong>{operation.task.title}</strong><div className="task-meta"><span><User size={13}/>{operation.task.executor}</span><span><Clock size={13}/>{operation.task.remainingMinutes===null?'Estimate needed':`${operation.task.remainingMinutes} min`}</span></div><p className="small"><Link2 size={12}/> {operation.task.dependencies.map(id=>allTasks.find(t=>t.id===id)?.title || id).join(', ') || 'No dependencies'}</p><p className="small muted">Proof: {operation.task.completionEvidence}</p>{operation.task.optional && <Badge>Optional</Badge>}</>}</>}
        {operation.type==='update_task' && <><div className="change-label"><ArrowRight size={14}/>{operation.patch.deferred?'Deferred':'Modified'} task</div><strong>{mission.tasks.find(t=>t.id===operation.taskId)?.title || operation.taskId}</strong>{editing&&<TaskPatchEditor operation={operation} tasks={allTasks} onChange={next=>changeOperation(index,next)}/>} {Object.entries(operation.patch).map(([key,value])=><p className="diff-value" key={key}><span>{readable(key)}</span><del>{formatValue((mission.tasks.find(t=>t.id===operation.taskId) as unknown as Record<string,unknown>|undefined)?.[key])}</del><ArrowRight size={12}/><ins>{formatValue(value)}</ins></p>)}</>}
        {operation.type==='add_criterion' && <><div className="change-label"><Check size={14}/>Added {operation.criterion.required?'required':'optional'} criterion</div>{editing?<><Field label="Criterion title"><input value={operation.criterion.title} onChange={e=>changeOperation(index,{...operation,criterion:{...operation.criterion,title:e.target.value}})}/></Field><Field label="Verification method"><input value={operation.criterion.verificationMethod} onChange={e=>changeOperation(index,{...operation,criterion:{...operation.criterion,verificationMethod:e.target.value}})}/></Field></>:<><strong>{operation.criterion.title}</strong><p className="small muted">Verification: {operation.criterion.verificationMethod}</p></>}</>}
        {operation.type==='update_criterion' && <><div className="change-label">Modified criterion</div><strong>{mission.criteria.find(c=>c.id===operation.criterionId)?.title || operation.criterionId}</strong>{Object.entries(operation.patch).map(([key,value])=><p className="diff-value" key={key}><span>{readable(key)}</span><del>{formatValue((mission.criteria.find(c=>c.id===operation.criterionId) as unknown as Record<string,unknown>|undefined)?.[key])}</del><ArrowRight size={12}/><ins>{formatValue(value)}</ins></p>)}</>}
        {operation.type==='update_contract' && <><div className="change-label">Modified contract</div>{editing&&operation.patch.deadline&&<Field label="Proposed exact deadline"><input type="datetime-local" value={localInput(operation.patch.deadline,mission.timezone)} onChange={e=>{if(e.target.value){try{changeOperation(index,{...operation,patch:{...operation.patch,deadline:zonedInputToIso(e.target.value,mission.timezone)}});setError('');}catch(error){setError(error instanceof Error?error.message:'Invalid local deadline.');}}}}/></Field>}{Object.entries(operation.patch).map(([key,value])=><p className="small" key={key}>{key==='deadline'?'Deadline':readable(key)}: {key==='deadline'&&typeof value==='string'?dateTime(value,mission.timezone):formatValue(value)}</p>)}</>}
      </div>)}</div>
      {proposal.kind==='recovery' && <p className="small muted">Unchanged work: {mission.tasks.filter(t=>!proposal.affectedRecordIds.includes(t.id)).map(t=>t.title).join(', ') || 'No other tasks.'}</p>}
      {proposal.scheduleNote && <Notice tone="amber">{formatTimestampsInText(proposal.scheduleNote,mission.timezone)}</Notice>}
      {stale && <Notice tone="amber">This review is stale or expired. Revalidate its changes against the current mission before approving.<div className="actions"><Button variant="secondary" busy={busy} onClick={()=>void run(()=>refreshProposal(proposal))}>Refresh proposal</Button></div></Notice>}
      {error && <Notice tone="red">{error}</Notice>}
      {pending && !stale && <div className="actions wrap">{editing?<><Button busy={busy} onClick={()=>void run(async()=>{await edit(proposal,operations);setEditing(false);})}>Save revised proposal</Button><Button variant="secondary" onClick={()=>{setEditing(false);setOperations(proposal.operations);}}>Cancel edits</Button></>:<><Button busy={busy} onClick={()=>void run(()=>approve(proposal))}>{proposal.kind==='plan'?'Approve and create tasks':'Approve changes'}</Button><Button variant="secondary" disabled={busy} onClick={()=>setEditing(true)}>Edit</Button><Button variant="ghost" disabled={busy} onClick={()=>void run(()=>reject(proposal))}>Reject</Button></>}</div>}
      <p className="small muted">Revision {proposal.baseRevision} · Review expires {dateTime(proposal.expiresAt)}</p>
    </div>
  </article>;
}
function formatValue(value:unknown):string {if(value===null)return 'Unknown';if(value===undefined)return '—';if(Array.isArray(value))return value.join(', ') || 'None';if(typeof value==='boolean')return value?'Yes':'No';return String(value);}

function TaskPatchEditor({operation,tasks,onChange}:{operation:Extract<ProposalOperation,{type:'update_task'}>;tasks:Task[];onChange:(operation:Extract<ProposalOperation,{type:'update_task'}>)=>void}) {
  const original=tasks.find(t=>t.id===operation.taskId);
  if(!original)return null;
  const patch=operation.patch;
  const current={...original,...patch};
  return <div className="task-patch-editor"><Field label="Proposed title"><input value={current.title} onChange={e=>onChange({...operation,patch:{...patch,title:e.target.value}})}/></Field><Field label="Remaining minutes"><input type="number" min="0" value={current.remainingMinutes??''} placeholder="Unknown" onChange={e=>onChange({...operation,patch:{...patch,remainingMinutes:e.target.value===''?null:Number(e.target.value)}})}/></Field>{'status' in patch&&<Field label="Proposed task status"><select value={current.status} onChange={e=>onChange({...operation,patch:{...patch,status:e.target.value as Task['status']}})}><option value="todo">Not started</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="reported_complete">Reported complete</option></select></Field>}{'deferred' in patch&&<label className="check-label"><input type="checkbox" checked={current.deferred} onChange={e=>onChange({...operation,patch:{...patch,deferred:e.target.checked}})}/>Defer this optional task</label>}<fieldset><legend>Dependencies</legend>{tasks.filter(t=>t.id!==operation.taskId).map(t=><label className="check-label" key={t.id}><input type="checkbox" checked={current.dependencies.includes(t.id)} onChange={e=>onChange({...operation,patch:{...patch,dependencies:e.target.checked?[...current.dependencies,t.id]:current.dependencies.filter(id=>id!==t.id)}})}/>{t.title}</label>)}</fieldset></div>;
}
