import {useEffect,useState} from 'react';
import {api,post} from '../api';
import {Badge,Button,Field,Notice} from '@mission/ui';
import type {RoutineSpec,RoutineSuggestion as Suggestion,RoutineRun} from '../../../../packages/domain/src/routines';

export function RoutineSuggestion({suggestion,onCreate,onDismiss,onSuppress}:{suggestion:Suggestion;onCreate:()=>void;onDismiss:()=>void;onSuppress:()=>void}){
 return <article className="proposal-card"><div className="proposal-body"><h3>Make this workflow repeatable</h3><Badge>{suggestion.fixture?'Comparable fixture runs':'Verified mission history'}</Badge><p>{suggestion.reason}</p><p className="small">Supporting runs: {suggestion.supportingRuns.join(', ')}</p>{suggestion.differences.map(d=><p key={d}>{d}</p>)}<div className="actions wrap"><Button onClick={onCreate}>Edit routine</Button><Button variant="secondary" onClick={onDismiss}>Dismiss</Button><Button variant="ghost" onClick={onSuppress}>Do not suggest this pattern</Button></div></div></article>;
}
export function RoutineEditor({routine,onSave,onPreview,onPause,busy=false}:{routine:RoutineSpec;onSave:(patch:Partial<RoutineSpec>)=>Promise<void>;onPreview:()=>Promise<void>;onPause:()=>Promise<void>;busy?:boolean}){
 const [title,setTitle]=useState(routine.title),[purpose,setPurpose]=useState(routine.purpose),[error,setError]=useState('');
 const [advanced,setAdvanced]=useState(JSON.stringify({trigger:routine.trigger,timezone:routine.timezone,filters:routine.filters,requiredInputs:routine.requiredInputs,parameterBindings:routine.parameterBindings,allowedSources:routine.allowedSources,steps:routine.steps,budget:routine.budget,exceptionPolicy:routine.exceptionPolicy,browserDependency:routine.browserDependency},null,2));
 async function act(fn:()=>Promise<void>){setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Routine update failed');}}
 return <article className="proposal-card"><div className="proposal-body"><h3>{routine.title}</h3><Badge>{routine.lifecycle} · version {routine.version}{routine.fixture?' · fixture':''}</Badge><Field label="Routine title"><input value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Purpose"><textarea value={purpose} maxLength={2000} onChange={e=>setPurpose(e.target.value)}/></Field><details><summary>Edit trigger, sources, steps and limits</summary><Field label="Routine specification (JSON)"><textarea rows={16} value={advanced} onChange={e=>setAdvanced(e.target.value)} spellCheck={false}/></Field><p className="small">Changes create a new draft requiring fresh review. Per-run reviews and pause-on-error policy remain mandatory.</p></details><p>Trigger: {routine.trigger} · {routine.timezone}</p><p>Browser dependency: {routine.browserDependency.replaceAll('_',' ')}</p><ol>{routine.steps.map(step=><li key={step.id}>{step.action} {step.app} → {step.destination}<p className="small">Audience: {step.audience.join(', ')} · Review every run</p></li>)}</ol><p className="small">Maximum {routine.budget.maxOperations} operations · one concurrent run · {routine.budget.cooldownSeconds}s cooldown</p><Notice tone="amber">Native enable is blocked pending authorized node schema and per-run approval verification. Preview performs no workspace writes.</Notice>{error&&<Notice tone="red">{error}</Notice>}<div className="actions wrap"><Button busy={busy} onClick={()=>void act(()=>onSave({...JSON.parse(advanced),title,purpose}))}>Save reviewed version</Button><Button variant="secondary" busy={busy} onClick={()=>void act(onPreview)}>Preview</Button><Button disabled title="Requires authorized native node schemas and execution scope">Enable native routine</Button>{routine.lifecycle!=='archived'&&<Button variant="ghost" busy={busy} onClick={()=>void act(onPause)}>Pause</Button>}</div></div></article>;
}
export function AutomationRunInspector({runs}:{runs:RoutineRun[]}){return <section aria-label="Automation run history"><h3>Automation runs</h3>{runs.length===0?<p>No native runs have been executed.</p>:runs.map(run=><article className="proposal-card" key={run.id}><div className="proposal-body"><Badge>{run.status.replaceAll('_',' ')}{run.fixture?' · fixture':''}</Badge><p>{run.detail}</p><p>Routine version {run.version}</p><p>{run.nativeRunId?`Native run: ${run.nativeRunId}`:'No native run ID'}</p><p>Artifact IDs: {run.artifactIds.join(', ')||'None verified'}</p></div></article>)}</section>;}

export function Routines({missionId}:{missionId?:string}){
 const [data,setData]=useState<{routines:RoutineSpec[];suggestions:Suggestion[];runs:RoutineRun[]}>({routines:[],suggestions:[],runs:[]});
 const [error,setError]=useState(''),[preview,setPreview]=useState<{productionWrites:number;blockers:string[]}|null>(null),[busy,setBusy]=useState(false);
 const refresh=async()=>setData(await api<typeof data>('/api/routines'));
 useEffect(()=>{void refresh().catch(e=>setError(e instanceof Error?e.message:'Could not load routines'));},[missionId]);
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(e instanceof Error?e.message:'Routine request failed');}finally{setBusy(false);}}
 return <section aria-label="Routines"><h2>Routines</h2><p>Turn consented, verified mission work into a reviewed proposal. Native activation requires additional verified access.</p>{error&&<Notice tone="red">{error}</Notice>}{missionId&&<Button busy={busy} onClick={()=>void act(()=>post(`/api/missions/${missionId}/routines`,{consent:true}))}>Make this repeatable</Button>}<p className="small muted">This action consents to retaining minimal approved execution metadata for pattern suggestions. No clickstreams or raw browser snapshots are collected for routines.</p><Button variant="secondary" busy={busy} onClick={()=>void act(()=>post('/api/routines/demo',{consent:true}))}>Load three comparable fixture runs</Button>{data.suggestions.map(s=><RoutineSuggestion key={s.patternKey} suggestion={s} onCreate={()=>void act(()=>post('/api/routines/from-history',{runId:s.supportingRuns[0]}))} onDismiss={()=>void act(()=>post('/api/routines/suggestions/dismiss',{patternKey:s.patternKey,permanent:false}))} onSuppress={()=>void act(()=>post('/api/routines/suggestions/dismiss',{patternKey:s.patternKey,permanent:true}))}/>)}{data.routines.map(r=><div id={`routine-${r.id}`} key={`${r.id}:${r.version}`}><RoutineEditor routine={r} busy={busy} onSave={patch=>act(()=>api(`/api/routines/${r.id}`,{method:'PATCH',body:JSON.stringify({...patch,version:r.version})}))} onPreview={()=>act(async()=>{const result=await post<{preview:{productionWrites:number;blockers:string[]}}>(`/api/routines/${r.id}/preview`);setPreview(result.preview);})} onPause={()=>act(()=>post(`/api/routines/${r.id}/pause`))}/></div>)}{!data.routines.length&&<p>No saved routines. Complete and verify a mission, then choose Make this repeatable.</p>}{preview&&<Notice tone="amber"><strong>Local preview · {preview.productionWrites} production writes</strong>{preview.blockers.map(b=><p key={b}>{b}</p>)}</Notice>}<AutomationRunInspector runs={data.runs}/></section>;
}
