import {useState} from 'react';
import {Button,Field,Notice} from '@mission/ui';
import {Cable,ExternalLink,ShieldCheck} from 'lucide-react';
import {api,BACKEND,post,writeSession} from '../api';
import type {Mission} from '@mission/domain';
import {modelProviderLabel,modelSetupHint,planningStatus,type ModelStatusConfig} from '../model-status';
export interface AppConfig extends ModelStatusConfig {mode:'fixture'|'live';providerMode?:'fixture'|'live';modelMode?:'fixture'|'live';modelEnabled?:boolean;missing?:string[];setupRequired?:string[];liveReady?:boolean;researchEnabled?:boolean;demoNow?:string|null;model?:string;provider?:{ready?:boolean;name?:string;identity?:unknown};capabilities?:unknown;[key:string]:unknown}
export function Settings({config,paired,onPaired,onClose,onRefresh,onSmoke,mission,onDelete}: {config:AppConfig|null;paired:boolean;onPaired:()=>Promise<void>;onClose:()=>void;onRefresh:()=>Promise<void>;onSmoke:(missionId:string)=>Promise<void>;mission:Mission|null;onDelete:()=>Promise<void>}) {
  const [code,setCode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [connection,setConnection]=useState<{identity?:{id?:string;workspaceId?:string;displayName?:string;verified?:boolean}|null;liveReady?:boolean;setupRequired?:string[]}|null>(null);
  const [deleteText,setDeleteText]=useState('');
  return <section className="settings-page"><div className="section-heading"><Cable size={22}/><div><h2>Connect your workspace</h2><p>A local server keeps mission state and provider credentials.</p></div></div>
    <div className="settings-section"><h3>Local server</h3><p><code>{BACKEND}</code></p><Notice tone={config?'blue':'amber'}>{config?`Task provider mode: ${config.providerMode || config.mode}. ${planningStatus(config)}.`:'Server is unavailable. Run pnpm dev in the repository.'}</Notice>
      {(config?.providerMode || config?.mode)==='fixture' && <p className="small muted">Task provider responses are simulated. Saved missions are real local database records. Live Ambiguous calls are not made.</p>}
      {config&&<p className="small muted">Selected live model provider: {modelProviderLabel(config)}{config.modelName?` · ${config.modelName}`:''}. {config.modelMode!=='live'?'Planning currently uses deterministic fixture suggestions. ':''}{!config.modelEnabled&&modelSetupHint(config)}</p>}
      {(config?.missing || []).map(item=><Notice tone="amber" key={item}>{item}</Notice>)}
      <Button variant="secondary" onClick={()=>void onRefresh()}>Refresh connection</Button>
      {paired&&<div className="settings-section"><h3>Provider identity</h3><p className="small muted">Inspect the connected identity before enabling any live task writes.</p><Button variant="secondary" busy={busy} onClick={async()=>{setBusy(true);setError('');try{setConnection(await api('/api/integrations/check'));}catch(e){setError(e instanceof Error?e.message:'Could not check provider identity.');}finally{setBusy(false);}}}>Check connected identity</Button>{connection&&<><p className="small">{connection.identity?`${connection.identity.displayName||connection.identity.id} · workspace ${connection.identity.workspaceId||'unverified'}`:'No verified provider identity is connected.'}</p><Notice tone={connection.liveReady?'blue':'amber'}>{connection.liveReady?'Live writes enabled for approved operations.':'Live writes are not enabled.'}</Notice>{connection.setupRequired?.map(item=><p className="small muted" key={item}>{item}</p>)}</>}</div>}
    </div>
    <div className="settings-section"><h3><ShieldCheck size={16}/> {paired?'Session paired':'Pair this browser session'}</h3><p className="small muted">Run <code>pnpm pairing-code</code> in the repository and enter the code. The session token is kept in browser session storage, never synchronized.</p>
      {!paired?<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const result=await post<{token:string}>('/api/pair',{code});await writeSession(result.token);setCode('');await onPaired();onClose();}catch(e){setError(e instanceof Error?e.message:'Pairing failed.');}finally{setBusy(false);}}}><Field label="Pairing code"><input required type="password" autoComplete="off" value={code} onChange={e=>setCode(e.target.value)}/></Field>{error && <Notice tone="red">{error}</Notice>}<Button type="submit" busy={busy}>Pair workspace</Button></form>:<Button variant="secondary" onClick={async()=>{setBusy(true);try{await post('/api/session/revoke');await writeSession(null);await onPaired();}catch(e){setError(e instanceof Error?e.message:'Could not revoke session.');}finally{setBusy(false);}}} busy={busy}>Revoke this session</Button>}
    </div>
    {paired&&<div className="settings-section"><h3>Verify a single approved task</h3><p className="small muted">Prepare a test mission with one task proposal. Review it before creation, then inspect its actual provider ID and read-back state. A supported update requires another approval.</p><Button variant="secondary" busy={busy} onClick={async()=>{setBusy(true);setError('');try{const result=await post<{mission:{id:string}}>('/api/integrations/smoke');await onSmoke(result.mission.id);onClose();}catch(e){setError(e instanceof Error?e.message:'Could not prepare the smoke test.');}finally{setBusy(false);}}}>Prepare provider smoke test</Button></div>}
    {paired&&mission&&<details className="settings-section"><summary>Delete local mission data</summary><p className="small">Delete “{mission.goal}” and its accepted evidence, proposals, and local activity. External provider task records remain. This cannot be undone.</p><Field label="Type DELETE to confirm"><input value={deleteText} autoComplete="off" onChange={e=>setDeleteText(e.target.value)}/></Field><Button variant="danger" disabled={deleteText!=='DELETE'} busy={busy} onClick={async()=>{setBusy(true);setError('');try{await onDelete();setDeleteText('');onClose();}catch(e){setError(e instanceof Error?e.message:'Could not delete the mission.');}finally{setBusy(false);}}}>Delete local mission</Button></details>}
    <p className="small muted">Only explicitly accepted excerpts are sent. Capture previews stay in the extension until you send them. No browsing history, form values, or private drafts are collected.</p>
    {error && paired && <Notice tone="red">{error}</Notice>}<div className="actions"><Button variant="secondary" onClick={onClose}>Back to missions</Button><a href={`${BACKEND}/privacy`} target="_blank" rel="noreferrer">Privacy notes <ExternalLink size={12}/></a></div>
  </section>;
}
