import {useEffect,useState} from 'react';
import type {Mission,Task} from '@mission/domain';
import {Badge,Button,Field,Notice} from '@mission/ui';
import {Bot,CheckCircle2,ChevronDown,Clock,ExternalLink,Link2,MoreHorizontal,User} from 'lucide-react';
import {dateTime,readable,taskLabels,tone} from '../format';

export function TaskList({mission,selectedId,onSelect,onBlock,onResolve,onEdit,onRetry,busy}: {mission:Mission;selectedId:string|null;onSelect:(id:string)=>void;onBlock:(id:string,reason:string)=>Promise<void>;onResolve:(id:string,resolution:string,remainingMinutes:number|null)=>Promise<void>;onEdit:(task:Task,patch:Partial<Task>)=>Promise<void>;onRetry:(operationId:string)=>Promise<void>;busy:boolean}) {
  return <ol className="task-list">{mission.tasks.map((task,index)=><TaskRow key={task.id} task={task} index={index} mission={mission} expanded={selectedId===task.id} onSelect={()=>onSelect(selectedId===task.id?'':task.id)} onBlock={reason=>onBlock(task.id,reason)} onResolve={(resolution,minutes)=>onResolve(task.id,resolution,minutes)} onEdit={patch=>onEdit(task,patch)} onRetry={onRetry} busy={busy}/>)}</ol>;
}
function TaskRow({task,index,mission,expanded,onSelect,onBlock,onResolve,onEdit,onRetry,busy}:{task:Task;index:number;mission:Mission;expanded:boolean;onSelect:()=>void;onBlock:(reason:string)=>Promise<void>;onResolve:(resolution:string,minutes:number|null)=>Promise<void>;onEdit:(patch:Partial<Task>)=>Promise<void>;onRetry:(operationId:string)=>Promise<void>;busy:boolean}) {
  const [reason,setReason]=useState('');const [editing,setEditing]=useState(false);const [title,setTitle]=useState(task.title);const [effort,setEffort]=useState(task.remainingMinutes===null?'':String(task.remainingMinutes));const [error,setError]=useState('');
  useEffect(()=>{if(!editing){setTitle(task.title);setEffort(task.remainingMinutes===null?'':String(task.remainingMinutes));}},[task.title,task.remainingMinutes,editing]);
  async function run(fn:()=>Promise<void>){setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Update failed.');}}
  return <li className={`task-row ${expanded?'is-expanded':''} ${task.deferred?'is-deferred':''}`}>
    <div className="task-number">{task.status==='reported_complete'?<CheckCircle2 size={18}/>:index+1}</div><div className="task-main"><div className="task-title-line"><button className="task-title" onClick={onSelect} aria-expanded={expanded}>{task.title}{task.optional?' (Optional)':''}</button><button aria-label={`Details for ${task.title}`} className="icon-button" onClick={onSelect}>{expanded?<ChevronDown size={17}/>:<MoreHorizontal size={17}/>}</button></div>
      <div className="task-meta"><Badge tone={tone(task.status)}>{task.deferred?'Deferred':task.blocker?'Blocked (local)':taskLabels[task.status]}</Badge><span>{task.executor==='agent'?<Bot size={14}/>:<User size={14}/>} {task.executor==='human'?'Human':'Agent'}</span><span><Clock size={14}/>{task.remainingMinutes===null?'Estimate needed':`${task.remainingMinutes} min`}</span><span className="dependency"><Link2 size={14}/>{task.dependencies.map(id=>`${mission.tasks.findIndex(t=>t.id===id)+1}. ${mission.tasks.find(t=>t.id===id)?.title||id}`).join(', ') || 'None'}</span></div>
      {task.provider&&task.provider.state!=='synced'&&<div className="task-sync-warning"><Badge tone={tone(task.provider.state)}>{readable(task.provider.state)}</Badge><span>{task.provider.state==='outcome_unknown'?'Provider outcome requires inspection before retry.':task.provider.error||'Provider synchronization needs attention.'}</span></div>}
      {expanded && <div className="task-detail"><p>{task.description}</p><p><strong>Completion evidence:</strong> {task.completionEvidence}</p><p className="small muted">Dependencies, executor, estimates, blockers, and evidence are Mission Control metadata.</p>
        <TaskSyncResult tasks={[task]}/>{mission.operations.filter(operation=>operation.taskId===task.id&&operation.state==='failed').slice(-1).map(operation=><Button key={operation.id} variant="secondary" busy={busy} onClick={()=>void run(()=>onRetry(operation.id))}>Retry failed synchronization</Button>)}
        {task.blocker && <Notice tone="amber">Reported blocker: {task.blocker}</Notice>}
        {editing?<div className="task-edit"><Field label="Title"><input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Remaining effort (minutes)" help="Leave blank when unknown"><input type="number" min="0" value={effort} onChange={e=>setEffort(e.target.value)}/></Field><Button busy={busy} onClick={()=>void run(async()=>{await onEdit({title,remainingMinutes:effort===''?null:Number(effort)});setEditing(false);})}>Propose task changes</Button></div>:<div className="actions wrap"><Button variant="secondary" disabled={busy} onClick={()=>setEditing(true)}>Edit task</Button>{task.status!=='reported_complete' && <Button variant="secondary" busy={busy} onClick={()=>void run(()=>onEdit({status:'reported_complete',remainingMinutes:0}))}>Propose reported complete</Button>}</div>}
        {task.status!=='reported_complete' && <div className="blocker-form"><Field label={task.blocker?'Report a resolution':'Report a blocker'} help="This records your report locally and recalculates the schedule."><input placeholder={task.blocker?'How was this blocker resolved?':'What is stopping this work?'} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field>{task.blocker&&<Field label="Remaining minutes after resolution"><input type="number" min="0" value={effort} placeholder="Unknown" onChange={e=>setEffort(e.target.value)}/></Field>}<Button variant="secondary" busy={busy} disabled={reason.trim().length<3} onClick={()=>void run(async()=>{if(task.blocker)await onResolve(reason,effort===''?null:Number(effort));else await onBlock(reason);setReason('');})}>{task.blocker?'Record blocker resolved':'Mark blocked'}</Button></div>}
        {error && <Notice tone="red">{error}</Notice>}
      </div>}
    </div>
  </li>;
}
export function TaskSyncResult({tasks}:{tasks:Task[]}) {
  return <div className="sync-results">{tasks.map(task=><div key={task.id} className="sync-result"><Badge tone={task.provider?tone(task.provider.state):'neutral'}>{task.provider?readable(task.provider.state):'Not created externally'}</Badge>{task.provider && <>{task.provider.id.startsWith('pending:')?<span className="small muted">Provider ID awaiting read-back</span>:<code>{task.provider.id}</code>}{task.provider.url && /^https?:\/\//.test(task.provider.url) && <a href={task.provider.url} target="_blank" rel="noreferrer">Open provider record <ExternalLink size={12}/></a>}{task.provider.observedStatus&&<span className="small muted">Provider reports: {readable(task.provider.observedStatus)}</span>}{task.provider.lastSyncedAt && <span className="small muted">Read back {dateTime(task.provider.lastSyncedAt)}</span>}{task.provider.error && <Notice tone="red">{task.provider.error}</Notice>}</>}</div>)}</div>;
}
