import { resolve } from 'node:path';
import { assertRuntimeConfig,config } from './config.js';
import { openDatabase } from './database.js';
import { FixtureWorkProvider,FileFixtureRepository,AmbiguousWorkProvider } from './providers/index.js';
import { MissionService } from './service.js';
import { createApp } from './app.js';
import type { ExecutionService } from './execution-service.js';
import { maintainHostedDemoData } from './demo-cleanup.js';
assertRuntimeConfig();
const db=await openDatabase();
const provider=config.PROVIDER_MODE==='fixture'?new FixtureWorkProvider(new FileFixtureRepository(resolve(config.dataDir,'provider-fixture.json'))):new AmbiguousWorkProvider({apiKey:config.AMBIGUOUS_API_KEY,expectedUserId:config.AMBIGUOUS_EXPECTED_USER_ID,expectedWorkspaceId:config.AMBIGUOUS_EXPECTED_WORKSPACE_ID});
const service=new MissionService(db,provider);
await service.recoverInterruptedOperations();
const app=await createApp(service);
const executionService=app.locals.executionService as ExecutionService;
const cleanup=async()=>{if(config.DEPLOYMENT_MODE==='hosted')await executionService.abortExpiredDemoRuns();await db.transaction(async q=>{await q('DELETE FROM temporary_context WHERE expires_at<=now()');if(config.DEPLOYMENT_MODE==='hosted')await maintainHostedDemoData(q,config.PUBLIC_DEMO_ENABLED);});};
await cleanup();
await executionService.listen();
const server=app.listen(config.PORT,config.host,()=>console.log(`MissionDeck listening on ${config.host}:${config.PORT} · deployment=${config.DEPLOYMENT_MODE} · provider=${config.PROVIDER_MODE} · model=${config.MODEL_MODE} · database=${config.DATABASE_MODE}.`));
void service.drain();
const contextCleanup=setInterval(()=>{void cleanup().catch(()=>{});},60_000);contextCleanup.unref();
for(const signal of ['SIGINT','SIGTERM'] as const)process.on(signal,()=>{clearInterval(contextCleanup);void executionService.stop().finally(()=>server.close(()=>{void db.close().then(()=>process.exit(0));}));});
