import {describe,it,expect} from 'vitest';
import {discoverRoutines,makeRepeatable,reviseRoutine,routineApprovalHash,executionMetadataSchema,type ExecutionMetadata} from '../../../packages/domain/src/routines.js';
import {previewRoutine,compileAutomation,approveRoutineActivation,checkRoutineEvent} from './routines.js';
const scope={ownerId:'owner',workspaceId:'workspace'};
const run=(n:number):ExecutionMetadata=>({id:`run-${n}`,missionId:`mission-${n}`,...scope,consented:true,verified:true,approved:true,fixture:true,family:'launch_review',steps:[{id:'brief',action:'update',app:'docs',sourceTypes:['page'],destination:'private-brief',audience:['owner'],sensitiveSources:['private-document'],review:'per_run',dependencies:[]}],corrections:[],failureCount:0,completedAt:'2026-09-12T12:00:00Z'});
const spec=()=>makeRepeatable(run(1),scope,'routine-1');
describe('consented routine discovery',()=>{
 it('requires separate missions and deduplicates repeated records',()=>{expect(discoverRoutines([run(1),run(1),run(2)],scope)).toHaveLength(0);expect(discoverRoutines([run(1),run(2),run(3),run(3)],scope)).toHaveLength(1);});
 it('normalizes step IDs while preserving audience and sensitive source differences',()=>{const third=run(3);third.steps[0].id='other';expect(discoverRoutines([run(1),run(2),third],scope)).toHaveLength(1);third.steps[0].audience=['external'];expect(discoverRoutines([run(1),run(2),third],scope)).toHaveLength(0);});
 it('respects dismissals and workspace boundaries',()=>{const runs=[run(1),run(2),run(3)];const key=discoverRoutines(runs,scope)[0].patternKey;expect(discoverRoutines(runs,scope,[key])).toEqual([]);expect(discoverRoutines(runs,{...scope,workspaceId:'other'})).toEqual([]);});
 it('never learns from unconsented, failed, corrected, or unapproved histories',()=>{for(const patch of [{consented:false},{failureCount:1},{approved:false},{verified:false},{corrections:['Wrong recipient']}])expect(discoverRoutines([run(1),run(2),{...run(3),...patch}],scope)).toEqual([]);});
 it('does not mix fixture runs with authentic runs or accept clickstreams',()=>{expect(discoverRoutines([run(1),run(2),{...run(3),fixture:false}],scope)).toEqual([]);expect(()=>executionMetadataSchema.parse({...run(1),keystrokes:'secret'})).toThrow();});
 it('supports one explicitly requested successful template',()=>{expect(spec().supportingRuns).toEqual(['run-1']);expect(()=>makeRepeatable({...run(1),verified:false},scope,'x')).toThrow();});
});
describe('routine preview and scope',()=>{
 it('preview never writes or claims native success',()=>{const preview=previewRoutine(spec());expect(preview.productionWrites).toBe(0);expect(preview.nativePayload).toBeNull();expect(preview.blockers.length).toBeGreaterThan(0);expect(()=>compileAutomation(spec())).toThrow('401');});
 it('rejects dependency cycles and unknown executable fields',()=>{const bad=spec();bad.steps[0].dependencies=['brief'];expect(()=>previewRoutine(bad)).toThrow();expect(()=>previewRoutine({...spec(),code:'fetch(secret)'} as never)).toThrow();});
 it('new versions invalidate approval and discard prior native bindings',()=>{const before=spec();const after=reviseRoutine(before,{title:'Changed',lifecycle:'enabled',workspaceId:'escape'});expect(after.version).toBe(2);expect(after.workspaceId).toBe(scope.workspaceId);expect(after.lifecycle).toBe('draft');expect(routineApprovalHash(before)).not.toBe(routineApprovalHash(after));});
 it('rejects stale, replayed and cross-workspace activation approvals',()=>{const s={...spec(),lifecycle:'awaiting_approval' as const};const approval={...scope,specHash:routineApprovalHash(s),expiresAt:'2026-09-13T00:00:00Z',used:false};for(const patch of [{used:true},{workspaceId:'other'},{specHash:'changed'},{expiresAt:'2020-01-01T00:00:00Z'}])expect(()=>approveRoutineActivation(s,{...approval,...patch},'2026-09-12T00:00:00Z')).toThrow('approval');expect(()=>approveRoutineActivation(s,approval,'2026-09-12T00:00:00Z')).toThrow('401');});
 it('guards duplicate events, self triggers, browser absence and authentication',()=>{const s={...spec(),lifecycle:'enabled' as const};const event={id:'event',...scope,authenticated:true,receivedAt:'2026-09-12T12:00:00Z'};const state={seenEventIds:[],running:0,browserAvailable:true,now:event.receivedAt};expect(checkRoutineEvent(s,event,state).status).toBe('awaiting_input');expect(checkRoutineEvent(s,event,{...state,browserAvailable:false}).status).toBe('waiting_for_browser_context');expect(checkRoutineEvent(s,{...event,authenticated:false},state).accepted).toBe(false);expect(checkRoutineEvent(s,{...event,originRoutineId:s.id},state).accepted).toBe(false);expect(checkRoutineEvent(s,event,{...state,seenEventIds:['event']}).accepted).toBe(false);expect(checkRoutineEvent(s,event,{...state,running:1}).accepted).toBe(false);});
});

it('does not copy session metadata from the authenticated principal into a routine',()=>{
 const run={id:'meta-run',missionId:'meta-mission',ownerId:'owner',workspaceId:'workspace',consented:true,verified:true,approved:true,fixture:true,family:'task_followup' as const,steps:[{id:'one',action:'create' as const,app:'tasks' as const,sourceTypes:[],destination:'private',audience:[],sensitiveSources:[],review:'per_run' as const,dependencies:[]}],corrections:[],failureCount:0,completedAt:'2026-09-12T16:00:00Z'};
 const principal={ownerId:'owner',workspaceId:'workspace',origin:'http://127.0.0.1:5173',tokenHash:'must-not-copy'};
 const routine=makeRepeatable(run,principal,'routine-one');expect(routine).not.toHaveProperty('tokenHash');expect(routine).not.toHaveProperty('origin');
});
