import {useCallback,useEffect,useRef,useState} from 'react';
import {CopilotKitProvider} from '@copilotkit/react-core/v2';
import type {Mission,MissionExecution as Execution,Proposal,ProposalOperation,Task} from '@mission/domain';
import {Badge,Button,Notice} from '@mission/ui';
import {Activity,ArrowUpRight,CalendarDays,CheckCircle2,ChevronDown,ClipboardList,Copy,FileText,Flag,FlaskConical,PanelLeftClose,Plus,RefreshCw,Settings as SettingsIcon,Sparkles,Target,X} from 'lucide-react';
import {api,ApiError,BACKEND,isExtension,post,readSession} from './api';
import {CAPTURE_LIMIT,INBOX_TTL,captureTextHash,validatePending,type PendingCapture} from './capture';
import {dateTime,healthLabels,readable,tone} from './format';
import {MissionContractCard,type ContractInput} from './components/ContractCard';
import {PlanReview,MissingRequirementCard,RecoveryPlanDiff} from './components/ProposalCards';
import {CompletionReview} from './components/CompletionReview';
import {TaskList} from './components/TaskList';
import {CapturePreview} from './components/CapturePreview';
import {CopilotBindings,LiveChat} from './components/Copilot';
import {Settings,type AppConfig} from './components/Settings';
import {NewTaskCard} from './components/NewTaskCard';
import {BrowserContextPanel} from './BrowserContextPanel';
import type {FrozenContext} from './context-session';
import {Routines} from './components/Routines';
import {ArtifactWorkspace} from './components/ArtifactWorkspace';
import {modelSetupHint,planningStatus} from './model-status';
import {MissionExecution} from './components/MissionExecution';

type Tab='execution'|'plan'|'evidence'|'artifacts'|'routines'|'activity';
interface HealthAssessment {health:string;reasons?:string[];schedule?:{eta?:string|null;qualifiedEta?:string|null;assumptions?:string[];issues?:string[]};verifiedCriteria?:number;totalRequired?:number}
const inboxKey='mission-control.pending-capture';

export default function App(){
  const busyRef=useRef(false);
  const [sharedContext,setSharedContext]=useState<(FrozenContext & {expiresAt:string})|null>(null);
  const revokedContextSessions=useRef(new Set<string>());
  const activeMissionRef=useRef<string|null>(null);
  const [config,setConfig]=useState<AppConfig|null>(null);const [token,setToken]=useState<string|null>(null);const [missions,setMissions]=useState<Mission[]>([]);const [mission,setMission]=useState<Mission|null>(null);const [health,setHealth]=useState<HealthAssessment|null>(null);
  const [planningOnly,setPlanningOnly]=useState(false);const [isExecution,setIsExecution]=useState(false);const [isAdaptive,setIsAdaptive]=useState(false);
  const [possibleDuplicates,setPossibleDuplicates]=useState<string[]>([]);const [taskSeed,setTaskSeed]=useState<{title:string;description:string}|null>(null);const [addingTask,setAddingTask]=useState(false);const [tab,setTab]=useState<Tab>('plan');const [selectedTask,setSelectedTask]=useState<string|null>(null);const [settings,setSettings]=useState(new URLSearchParams(location.search).has('settings'));const [creating,setCreating]=useState(false);const [verify,setVerify]=useState(false);const [capture,setCapture]=useState<PendingCapture|null>(null);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [copilotOpen,setCopilotOpen]=useState(false);

  activeMissionRef.current=mission?.id??null;
  const shareContext=useCallback(async(frozen:FrozenContext)=>{const {missionId,...body}=frozen;const result=await post<FrozenContext & {expiresAt:string}>(`/api/missions/${missionId}/context`,{...body,sharingMode:'automatic',consented:true});if(activeMissionRef.current===missionId&&!revokedContextSessions.current.has(frozen.sessionId))setSharedContext(result);},[]);
  const clearContext=useCallback(async(sessionId:string,afterPending?:Promise<void>)=>{revokedContextSessions.current.add(sessionId);setSharedContext(current=>current?.sessionId===sessionId?null:current);const id=activeMissionRef.current;await afterPending?.catch(()=>{});if(id)await api(`/api/missions/${id}/context/${sessionId}`,{method:'DELETE'});},[]);
  useEffect(()=>{setSharedContext(null);},[mission?.id,token]);
  useEffect(()=>{if(!sharedContext)return;const timer=setTimeout(()=>setSharedContext(null),Math.max(0,Date.parse(sharedContext.expiresAt)-Date.now()));return()=>clearTimeout(timer);},[sharedContext]);
  const loadMission=useCallback(async(id:string)=>{const [result,executionResult]=await Promise.all([api<{mission:Mission;health:HealthAssessment}>(`/api/missions/${encodeURIComponent(id)}`),api<{execution:Execution|null}>(`/api/missions/${encodeURIComponent(id)}/execution`).catch(()=>({execution:null}))]);setMission(result.mission);setHealth(result.health);localStorage.setItem('mission-control.selected',id);setMissions(list=>list.some(m=>m.id===id)?list.map(m=>m.id===id?result.mission:m):[...list,result.mission]);setIsExecution(!!executionResult.execution);setIsAdaptive(!!executionResult.execution?.adaptive);setTab(current=>executionResult.execution?(executionResult.execution.adaptive&&current==='evidence'?'evidence':'execution'):current==='execution'?'plan':current);return {mission:result.mission,execution:executionResult.execution};},[]);
  const refresh=useCallback(async()=>{setError('');try{const nextConfig=await api<AppConfig>('/api/config');setConfig(nextConfig);const session=await readSession();setToken(session);if(session){const result=await api<{missions:Mission[]}>('/api/missions');setMissions(result.missions);const selected=localStorage.getItem('mission-control.selected');const next=result.missions.find(m=>m.id===selected)||result.missions[0];if(next)await loadMission(next.id);else setMission(null);}else{setMissions([]);setMission(null);}}catch(e){setError(e instanceof Error?e.message:'Unable to load workspace.');if(e instanceof ApiError&&e.status===401){setToken(null);setSettings(true);}}finally{setLoading(false);}},[loadMission]);
  useEffect(()=>{void refresh();},[refresh]);
  useEffect(()=>{
    if(!isExtension)return;
    const receive=async()=>{const values=await chrome.storage.session.get([inboxKey,'mission-control.capture-error']);const pending=validatePending(values[inboxKey]);if(pending)setCapture(pending);else if(values[inboxKey])await chrome.storage.session.remove(inboxKey);if(values['mission-control.capture-error']){setError(String(values['mission-control.capture-error']));await chrome.storage.session.remove('mission-control.capture-error');}};
    void receive();const listener=(changes:Record<string,chrome.storage.StorageChange>,area:string)=>{if(area==='session'&&(changes[inboxKey]||changes['mission-control.capture-error']))void receive();};chrome.storage.onChanged.addListener(listener);return()=>chrome.storage.onChanged.removeListener(listener);
  },[]);
  useEffect(()=>{if(!capture)return;const timeout=setTimeout(()=>{setCapture(null);setNotice('The unsent capture expired and was cleared. Capture again when ready.');if(isExtension)void chrome.storage.session.remove(inboxKey);},Math.max(0,capture.expiresAt-Date.now()));return()=>clearTimeout(timeout);},[capture]);
  async function action(fn:()=>Promise<void>){if(busyRef.current)throw new Error('Another operation is in progress. Wait for it to finish, then retry.');busyRef.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Something went wrong. Please retry.');if(e instanceof ApiError && e.status===409 && mission)await loadMission(mission.id).catch(()=>{});throw e;}finally{busyRef.current=false;setBusy(false);}}
  const run=(fn:()=>Promise<void>)=>void action(fn).catch(()=>{});
  async function write(path:string,body:unknown={}){await post(path,body);if(mission)await loadMission(mission.id);}
  async function confirmContract(input:ContractInput){await action(async()=>{const result=mission&&!creating?await post<{mission:Mission}>(`/api/missions/${mission.id}/contract`,input):await post<{mission:Mission}>('/api/missions',input);setCreating(false);await loadMission(result.mission.id);await post(`/api/missions/${result.mission.id}/plan`);await loadMission(result.mission.id);setCopilotOpen(true);});}
  const approve=async(proposal:Proposal)=>action(async()=>{if(!mission)return;await write(`/api/missions/${mission.id}/proposals/${proposal.id}/approve`,{payloadHash:proposal.payloadHash});setNotice('Approval recorded. Review each task’s provider read-back state for the result.');});
  const reject=async(proposal:Proposal)=>action(async()=>{if(!mission)return;await write(`/api/missions/${mission.id}/proposals/${proposal.id}/reject`);setNotice('Proposal rejected.');});
  const edit=async(proposal:Proposal,operations:ProposalOperation[])=>action(async()=>{if(!mission)return;await api(`/api/missions/${mission.id}/proposals/${proposal.id}`,{method:'PATCH',body:JSON.stringify({operations})});await loadMission(mission.id);setNotice('Revised proposal saved. Review it again before approval.');});
  const verifyCriterion=async(id:string,attestation:string)=>action(async()=>{if(mission)await write(`/api/missions/${mission.id}/criteria/${id}/verify`,{attestation});});
  const complete=async()=>action(async()=>{if(mission){await write(`/api/missions/${mission.id}/complete`);setNotice('Mission completed with verified required outcomes.');}});
  const discard=()=>{setCapture(null);if(isExtension)void chrome.storage.session.remove(inboxKey);};
  const manual=()=>setCapture({text:'',sourceUrl:'',title:'Personal note',capturedAt:new Date().toISOString(),method:'manual',truncated:false,expiresAt:Date.now()+INBOX_TTL});
  async function capturePage(){if(!isExtension){setNotice('Page capture runs in the installed Chrome extension. Add a manual excerpt in this full-page preview.');manual();return;}setError('');try{const result=await chrome.runtime.sendMessage({type:'CAPTURE_ACTIVE_TAB'});if(result?.error)throw new Error(result.error);const pending=validatePending(result?.capture);if(!pending)throw new Error('Capture was invalid or expired. Try again.');setCapture(pending);await chrome.storage.session.set({[inboxKey]:pending});}catch(e){setError(e instanceof Error?e.message:'Page capture unavailable. Add text manually.');}}
  async function sendCapture(id:string,pending:PendingCapture){await action(async()=>{const result=await post<{duplicate?:boolean;proposal?:Proposal;mission:Mission;summary?:string;possibleDuplicateEvidenceIds?:string[]}>(`/api/missions/${id}/evidence`,{text:pending.text.slice(0,CAPTURE_LIMIT),contentHash:await captureTextHash(pending.text.slice(0,CAPTURE_LIMIT)),title:pending.title,sourceUrl:pending.sourceUrl || null,capturedAt:pending.capturedAt,captureMethod:pending.method,truncated:pending.truncated,fixture:pending.sourceUrl.startsWith(BACKEND+'/fixtures/')});discard();setPossibleDuplicates(result.possibleDuplicateEvidenceIds||[]);const loaded=await loadMission(id);setCreating(false);if(loaded.execution?.adaptive){setTab(tab==='execution'?'execution':'evidence');setCopilotOpen(false);setAddingTask(false);setTaskSeed(null);setNotice(result.duplicate?'This excerpt is already saved in your mission. Import it from Update sources when you want it included in the next source revision.':'Excerpt saved for this mission. Open Execute → Update sources to preview and import it into the next source revision.');return;}setTab('plan');setCopilotOpen(true);if(pending.intent==='task'&&!result.proposal&&!result.duplicate&&!result.possibleDuplicateEvidenceIds?.length){setTaskSeed({title:pending.text.split('\n')[0]!.slice(0,120),description:pending.text.slice(0,4000)});setAddingTask(true);}
    setNotice(result.duplicate?'This exact evidence is already in your mission. No duplicate task was created.':result.proposal?'Evidence saved. Review its proposed impact before making changes.':result.summary||'Evidence saved. No new task was proposed.');});}
  const pendingProposals=mission?.proposals.filter(p=>p.state==='pending')||[];
  const proposals=pendingProposals.length?pendingProposals:(mission?.proposals.filter(p=>p.state==='stale'&&p.operations.some(o=>o.type==='add_task'?!mission.tasks.some(t=>t.id===o.task.id):o.type==='add_criterion'?!mission.criteria.some(c=>c.id===o.criterion.id):true)).slice(-1)||[]);
  const verifiedCount=mission?.criteria.filter(c=>c.required&&c.verificationState==='verified').length||0;
  const requiredCount=mission?.criteria.filter(c=>c.required).length||0;
  const modelLive=config?.modelEnabled===true && !!token;
  const selectedNav=creating?null:mission?.id;
  const beginMission=()=>{setCreating(true);setPlanningOnly(false);setSettings(false);setVerify(false);setAddingTask(false);};
  const executionStarted=async(id:string)=>{await loadMission(id);setCreating(false);setPlanningOnly(false);setIsExecution(true);setTab('execution');setCopilotOpen(false);};
  const generatePlan=async()=>action(async()=>{if(mission){await write(`/api/missions/${mission.id}/plan`);setCopilotOpen(true);}});
  const proposeRecovery=async()=>action(async()=>{if(mission){await write(`/api/missions/${mission.id}/recovery`);setCopilotOpen(true);}});
  const refreshProposal=async(proposal:Proposal)=>action(async()=>{if(mission){await write(`/api/missions/${mission.id}/proposals/${proposal.id}/refresh`);setNotice('Proposal revalidated. Review the current diff before approval.');}});
  const proposalActions={approve,reject,edit,refreshProposal,busy};

  const workspace=<div className="app-shell">
    <aside className="sidebar"><Brand/><nav aria-label="Missions">{missions.map(m=><button className={`mission-nav ${selectedNav===m.id?'active':''}`} key={m.id} onClick={()=>run(async()=>{await loadMission(m.id);setCreating(false);setSettings(false);setVerify(false);setSelectedTask(null);setAddingTask(false);setPossibleDuplicates([]);})}><span className="mission-nav-dot"/>{m.goal}</button>)}<button className="new-mission-nav" onClick={beginMission}><Plus size={18}/>New mission</button></nav><div className="sidebar-bottom"><button onClick={()=>setSettings(true)}><SettingsIcon size={18}/>Settings</button><div className="fixture-status"><FlaskConical size={18}/>{config?.mode==='live'?'Live providers':'Fixture providers'}<span className={`status-dot ${config?.mode==='live'?'live':''}`}/></div><p>{planningStatus(config)}<br/>Mission state stays on your server.</p></div></aside>
    <div className="workspace"><header className="mobile-header"><Brand compact/><select aria-label="Switch mission" value={creating?'':mission?.id||''} onChange={e=>{if(e.target.value==='new'){beginMission();return;}run(async()=>{await loadMission(e.target.value);setCreating(false);setVerify(false);setAddingTask(false);setSelectedTask(null);setPossibleDuplicates([]);});}}><option value="" disabled>Choose mission</option>{missions.map(m=><option key={m.id} value={m.id}>{m.goal}</option>)}<option value="new">+ New mission</option></select><button className="icon-button" aria-label="Settings" onClick={()=>setSettings(true)}><SettingsIcon size={18}/></button>{isExtension&&<button className="icon-button" aria-label="Open full workspace" onClick={()=>void chrome.tabs.create({url:chrome.runtime.getURL('index.html')})}><ArrowUpRight size={18}/></button>}</header>
    {settings?<div className="single-column"><Settings mission={mission} onDelete={async()=>{if(!mission)return;await api(`/api/missions/${mission.id}`,{method:'DELETE'});setMission(null);setHealth(null);await refresh();}} config={config} paired={!!token} onPaired={refresh} onClose={()=>setSettings(false)} onRefresh={refresh} onSmoke={async id=>{await loadMission(id);setCreating(false);setCopilotOpen(true);}}/></div>:<>
      {mission&&!creating?<header className="mission-header"><div><div className="headline"><h1>{mission.goal}</h1>{!isExecution&&<Badge tone={tone(mission.health)}>{mission.lifecycle==='completed'?'Completed':healthLabels[mission.health]}</Badge>}</div>{isExecution?<p className="small muted">No deadline set · Tasks, reviews, and saved deliverables in Ambiguous.</p>:<div className="mission-meta"><span><CalendarDays size={15}/>{dateTime(mission.deadline,mission.timezone)} · {mission.timezone}</span><span><ClipboardList size={15}/>{verifiedCount} of {requiredCount} verified</span></div>}</div>{(!isExecution||isAdaptive)&&<div className="header-actions"><Button variant="secondary" onClick={()=>void capturePage()}><Copy size={16}/>Capture page</Button>{isAdaptive&&<Button variant="secondary" onClick={manual}><Plus size={15}/>Add note</Button>}{!isExecution&&<Button busy={busy} onClick={()=>run(async()=>{await write(`/api/missions/${mission.id}/sync`);setNotice('Sync finished. Check task details for individual results.');})}><RefreshCw size={16}/>Sync now</Button>}</div>}</header>:<header className="mission-header"><div><h1>{creating?'New mission':'Your next mission starts here'}</h1><p className="muted">Plan. Capture. Ship.</p></div></header>}
      <div className="global-feedback">{error&&<Notice tone="red"><div className="row-between"><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={14}/></button></div><div className="actions"><Button variant="secondary" onClick={()=>void refresh()}>Retry</Button><Button variant="ghost" onClick={manual}>Add text manually</Button></div></Notice>}{notice&&<Notice tone="blue">{notice}</Notice>}{possibleDuplicates.length>0&&<Notice tone="amber">Possible duplicate evidence. Review the similar accepted excerpts before adding more work. <button className="text-button" onClick={()=>{setTab('evidence');setVerify(false);}}>Review evidence</button></Notice>}{config&&<div className="mode-strip"><FlaskConical size={13}/><strong>{config.mode==='fixture'?'Fixture providers':'Live providers'}</strong> · {planningStatus(config)}. <button onClick={()=>setSettings(true)}>Integration settings</button></div>}{!token&&!loading&&<Notice tone="amber">Pair this browser session to save and open missions. <button className="text-button" onClick={()=>setSettings(true)}>Connect workspace</button></Notice>}</div>
      {mission&&!creating&&<nav className="tabs" aria-label="Mission sections">{((isExecution?(isAdaptive?['execution','evidence','activity']:['execution','activity']):config?.workspaceUpgradeEnabled===false?['plan','evidence','activity']:['plan','execution','evidence','artifacts','routines','activity']) as Tab[]).map(t=><button key={t} aria-current={tab===t?'page':undefined} className={tab===t?'active':''} onClick={()=>{setTab(t);setVerify(false);}}>{t==='execution'?'Execute':t[0]!.toUpperCase()+t.slice(1)}{t==='evidence'&&mission.evidence.length>0&&<span>{mission.evidence.length}</span>}</button>)}</nav>}
      {loading?<div className="loading-state"><RefreshCw className="spin" size={22}/><p>Opening your workspace…</p></div>:<div className={`content-grid ${!mission||creating||tab==='execution'||isExecution?'content-grid--single':''}`}>
        <main>
          {addingTask&&mission&&<NewTaskCard key={mission.id} seed={taskSeed} mission={mission} onPropose={input=>action(async()=>{await write(`/api/missions/${mission.id}/tasks/propose`,input);setCopilotOpen(true);})} onCancel={()=>setAddingTask(false)} busy={busy}/>}
          {mission&&!creating&&!isExecution&&tab!=='execution'&&token&&config?.workspaceUpgradeEnabled!==false&&<BrowserContextPanel key={mission.id} missionId={mission.id} onReview={setCapture} onShared={shareContext} onClear={clearContext}/>}
          {capture&&<CapturePreview key={capture.capturedAt} capture={capture} missions={missions} missionId={mission?.id||null} onSend={sendCapture} onDiscard={discard} busy={busy}/>}
          {creating?planningOnly?<MissionContractCard onConfirm={confirmContract} onCancel={()=>setPlanningOnly(false)} busy={busy}/>:<MissionExecution paired={!!token} onStarted={executionStarted} onNewMission={beginMission} onCancel={()=>setCreating(false)} onPlanningSetup={()=>setPlanningOnly(true)}/>:!mission?<section className="empty-state"><div className="empty-symbol"><Target size={34}/></div><h2>Turn your mission into finished work.</h2><p>State the outcome. Assign a human and agent. Keep the work and its artifacts in Ambiguous.</p><div className="actions wrap"><Button disabled={!token} onClick={beginMission}><Plus size={16}/>Create a mission</Button><Button variant="secondary" disabled={!token||config?.mode!=='fixture'} busy={busy} onClick={()=>run(async()=>{const result=await post<{mission:Mission}>('/api/missions/demo');await loadMission(result.mission.id);})}>Start demo mission</Button></div><div className="empty-process"><span><Flag size={17}/>Define the outcome</span><span><Copy size={17}/>Assign the work</span><span><CheckCircle2 size={17}/>Verify the outcome</span></div><p className="small muted">The demo uses illustrative dates and simulated provider records.</p></section>:tab==='execution'?<MissionExecution key={mission.id} missionId={mission.id} paired={!!token} onStarted={executionStarted} onNewMission={beginMission}/>:!mission.contract.confirmed?<MissionContractCard key={mission.id} mission={mission} onConfirm={confirmContract} busy={busy}/>:verify?<CompletionReview mission={mission} onVerify={verifyCriterion} onComplete={complete} busy={busy}/>:tab==='plan'?<section className="plan-panel"><div className="section-heading row-between"><div><h2>Mission plan</h2><p>{mission.tasks.length} tasks · {mission.tasks.filter(t=>t.status==='reported_complete').length} reported complete</p></div><Button variant="secondary" busy={busy} onClick={()=>{if(mission.tasks.length){setTaskSeed(null);setAddingTask(true);}else void generatePlan().catch(()=>{});}}><Plus size={16}/>{mission.tasks.length?'Add task':'Generate plan'}</Button></div>
            {mission.tasks.length?<TaskList mission={mission} selectedId={selectedTask} onSelect={setSelectedTask} onBlock={(id,reason)=>action(async()=>{await write(`/api/missions/${mission.id}/tasks/${id}/block`,{reason});setNotice('Blocker recorded locally. Review recovery options.');})} onResolve={(id,resolution,remainingMinutes)=>action(async()=>{await write(`/api/missions/${mission.id}/tasks/${id}/resolve`,{resolution,remainingMinutes});setNotice('Blocker resolution recorded locally.');})} onRetry={operationId=>action(async()=>{await write(`/api/missions/${mission.id}/operations/${operationId}/retry`);})} onEdit={(task,patch)=>action(async()=>{await write(`/api/missions/${mission.id}/tasks/${task.id}/propose`,patch);setCopilotOpen(true);})} busy={busy}/>:<div className="plan-empty"><ClipboardList size={27}/><h3>Your plan is ready for a decision.</h3><p>Review the proposed tasks, estimates, and dependencies in Mission copilot. Nothing is created externally until you approve.</p></div>}
            <div className="plan-footer"><Button variant="secondary" busy={busy} onClick={()=>{if(mission.lifecycle==='completed')run(()=>write(`/api/missions/${mission.id}/reopen`));else setVerify(true);}}><CheckCircle2 size={16}/>{mission.lifecycle==='completed'?'Reopen mission':'Verify completion'}</Button><Button variant="ghost" busy={busy} onClick={()=>void proposeRecovery().catch(()=>{})}>Review recovery options</Button></div>
            {health&&<details className="schedule-details"><summary>Schedule & assumptions</summary>{health.reasons?.map(reason=><p key={reason}>{reason}</p>)}{health.schedule?.eta&&<p>Provisional finish: {dateTime(health.schedule.eta,mission.timezone)}</p>}{!health.schedule?.eta&&<p>No confirmed finish estimate is available.</p>}{health.schedule?.assumptions?.map(a=><p className="small muted" key={a}>{a}</p>)}</details>}
          </section>:tab==='routines'?<Routines missionId={mission.id}/>:tab==='artifacts'?<ArtifactWorkspace mission={mission}/>:tab==='evidence'?<section className="evidence-panel"><div className="section-heading row-between"><div><h2>Accepted evidence</h2><p>{isAdaptive?'Saved excerpts are available to preview and import from Execute → Update sources.':'Excerpts you chose to share with this mission.'}</p></div><Button variant="secondary" onClick={manual}><Plus size={15}/>Add note</Button></div>{!mission.evidence.length?<div className="plan-empty"><FileText size={28}/><h3>Give your mission context.</h3><p>Capture a requirement from a page or add a note. Review every excerpt before sending.</p><Button onClick={()=>void capturePage()}>Capture page</Button></div>:mission.evidence.map(e=><article className={`evidence-row ${possibleDuplicates.includes(e.id)?'evidence-row--similar':''}`} key={e.id}><div className="row-between"><h3>{e.title}</h3>{e.fixture&&<Badge tone="amber">Fixture</Badge>}</div><blockquote>{e.excerpt}</blockquote>{e.sourceUrl&&<a href={e.sourceUrl} target="_blank" rel="noreferrer">{e.sourceUrl}</a>}<p className="small muted">{readable(e.captureMethod)} · Captured {dateTime(e.capturedAt)} · {e.retention==='excerpt'?'Excerpt retained':'Retained until mission deletion'}{e.truncated?' · Truncated':''}</p>{Date.now()-new Date(e.capturedAt).getTime()>7*86400000&&<Notice tone="amber">This evidence is more than seven days old. Recheck time-sensitive requirements.</Notice>}</article>)}</section>:<section className="activity-panel"><div className="section-heading"><Activity size={18}/><div><h2>Mission activity</h2><p>Decisions, approvals, and synchronization history.</p></div></div>{!mission.events.length?<p className="muted">Your mission's decisions will appear here.</p>:<ol className="activity-list">{[...mission.events].reverse().map(event=><li key={event.id}><span className="activity-dot"/><div><p>{event.summary}</p><span className="small muted">{dateTime(event.timestamp)} · {event.actorId}</span></div></li>)}</ol>}</section>}
        </main>
        {mission&&!creating&&!isExecution&&tab!=='execution'&&<aside className={`copilot-panel ${copilotOpen?'copilot-panel--open':''}`}><button className="copilot-heading" onClick={()=>setCopilotOpen(!copilotOpen)} aria-expanded={copilotOpen}><span><Sparkles size={19}/>Mission copilot</span><span>{proposals.length>0&&<Badge tone="amber">{pendingProposals.length?`${pendingProposals.length} pending`:'Needs refresh'}</Badge>}<ChevronDown size={15}/></span></button><div className="copilot-content"><p className="copilot-intro">Keep the outcome in view. Review proposed changes, then choose what moves forward.</p>
          {proposals.length?<div className="proposal-stack">{proposals.map(proposal=>proposal.kind==='requirement'?<MissingRequirementCard key={proposal.id} mission={mission} proposal={proposal} {...proposalActions}/>:proposal.kind==='recovery'?<RecoveryPlanDiff key={proposal.id} mission={mission} proposal={proposal} {...proposalActions}/>:<PlanReview key={proposal.id} mission={mission} proposal={proposal} {...proposalActions}/>)}</div>:<div className="copilot-empty"><Sparkles size={24}/><p>No changes waiting for approval.</p><span className="small muted">Capture new requirements or review a blocker to see its impact here.</span></div>}
          {modelLive?<LiveChat/>:<div className="chat-unavailable"><p><Sparkles size={15}/>CopilotKit conversation</p><textarea disabled aria-label="Copilot unavailable" placeholder={config?.modelEnabled?'Pair this session to enable conversation':`${planningStatus(config)} · conversation is disabled`}/><span className="small muted">{config?.modelEnabled?'Pair this browser session in Settings to use conversation.':modelSetupHint(config)}</span></div>}
        </div></aside>}
      </div>}
    </>}
    <footer className="mobile-footer"><span><FlaskConical size={14}/>{config?.mode==='live'?'Live providers':'Fixture providers'} · Server-persisted missions</span><button onClick={()=>setSettings(true)}>Settings</button></footer>
    </div>
  </div>;
  // The same controlled cards remain available after chat disconnects because proposals live on the server.
  if(!modelLive)return workspace;
  return <CopilotKitProvider enableInspector={false} runtimeUrl={`${BACKEND}/api/copilotkit`} useSingleEndpoint={false} headers={token?{Authorization:`Bearer ${token}`}:{}}>{mission&&!isExecution&&<CopilotBindings sharedContext={sharedContext?.missionId===mission.id?sharedContext:null} mission={mission} selectedTaskId={selectedTask} onSelectTask={setSelectedTask} onTab={setTab} onConfirm={confirmContract} onVerify={verifyCriterion} onComplete={complete} onGeneratePlan={generatePlan} onProposeRecovery={proposeRecovery} health={health} live={modelLive} {...proposalActions}/>} {workspace}</CopilotKitProvider>;
}
function Brand({compact=false}:{compact?:boolean}){return <div className={`brand ${compact?'brand--compact':''}`}><span className="brand-mark">M</span><div><strong>Mission Control</strong>{!compact&&<span>Plan. Capture. Ship.</span>}</div></div>;}
