import {useEffect,useState,useRef} from 'react';
import {Button,Notice} from '@mission/ui';
import type {PendingCapture} from './capture';
import {validateCrop} from './screenshot';
import type {ContextSnapshot,FrozenContext} from './context-session';
/** Only reviewed snapshots cross into the existing evidence flow. Picker metadata stays local. */
export function BrowserContextPanel({missionId,onReview,onShared,onClear}:{missionId:string;onReview:(capture:PendingCapture)=>void;onShared?:(context:FrozenContext)=>Promise<void>;onClear?:(sessionId:string,afterPending?:Promise<void>)=>Promise<void>}){
 const [tabs,setTabs]=useState<chrome.tabs.Tab[]>([]),[selected,setSelected]=useState<number[]>([]),[sources,setSources]=useState<ContextSnapshot[]>([]),[live,setLive]=useState(false),[error,setError]=useState(''),[sites,setSites]=useState<string[]>([]);
 const [automatic,setAutomatic]=useState(false),[shot,setShot]=useState<string|null>(null),[shotSource,setShotSource]=useState(''); const sharedSession=useRef(''), sharedHash=useRef('');
 const generation=useRef(0), sharingAllowed=useRef(false), transmission=useRef(Promise.resolve());
 function clearShared(){const id=sharedSession.current;sharedSession.current='';sharedHash.current='';if(id){const pending=transmission.current.catch(()=>{});transmission.current=onClear?.(id,pending)??pending;}return transmission.current;}
 const [crop,setCrop]=useState({x:0,y:0,width:1,height:1});
 function cropShot(){const img=shotImage.current;if(!img)return;try{validateCrop(crop,img.naturalWidth,img.naturalHeight);const canvas=document.createElement('canvas');canvas.width=crop.width;canvas.height=crop.height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image editing unavailable.');ctx.drawImage(img,crop.x,crop.y,crop.width,crop.height,0,0,crop.width,crop.height);setShot(canvas.toDataURL('image/png'));setCrop({x:0,y:0,width:crop.width,height:crop.height});}catch(e){setError(String(e));}}
 const shotImage=useRef<HTMLImageElement>(null); const [redaction,setRedaction]=useState(false);
 function redactShot(event:React.MouseEvent<HTMLImageElement>){if(!redaction||!shotImage.current)return;const img=shotImage.current;const rect=img.getBoundingClientRect();const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.drawImage(img,0,0);ctx.fillStyle='#000';const scale=img.naturalWidth/rect.width;ctx.fillRect((event.clientX-rect.left-50)*scale,(event.clientY-rect.top-20)*scale,100*scale,40*scale);setShot(canvas.toDataURL('image/png'));}
 const extension=typeof chrome!=='undefined'&&!!chrome.runtime?.id;
 async function refresh(ids=selected,continuous=true){const epoch=generation.current;const result=await chrome.runtime.sendMessage({type:'CONTEXT_REFRESH',tabIds:ids});if(epoch!==generation.current)return;if(result.error)throw new Error(result.error);if(result.missionId!==missionId){setLive(false);setSources([]);await clearShared();return;}setSources(result.snapshots||[]);setLive(continuous&&!result.paused);setError((result.errors||[]).join(' '));if(result.paused){generation.current++;await clearShared();return;}if(sharingAllowed.current&&onShared){const hash=JSON.stringify((result.snapshots||[]).map((s:ContextSnapshot)=>[s.sourceUrl,s.contentHash]));if(hash!==sharedHash.current){const response=await chrome.runtime.sendMessage({type:'CONTEXT_FREEZE',requestId:crypto.randomUUID()});if(epoch!==generation.current||!sharingAllowed.current)return;if(response.error)throw new Error(response.error);sharedSession.current=result.sessionId;sharedHash.current=hash;transmission.current=transmission.current.catch(()=>{}).then(async()=>{if(epoch===generation.current&&sharingAllowed.current)await onShared(response.frozen);});await transmission.current;}}}
 async function pause(){generation.current++;sharingAllowed.current=false;setAutomatic(false);setLive(false);setSources([]);setShot(null);const cleared=clearShared();await chrome.runtime.sendMessage({type:'CONTEXT_PAUSE'});await cleared;}
 useEffect(()=>{generation.current++;sharingAllowed.current=false;setSources([]);setLive(false);setAutomatic(false);void clearShared();if(extension)void chrome.runtime.sendMessage({type:'CONTEXT_PAUSE'});return()=>{generation.current++;sharingAllowed.current=false;void clearShared();if(extension)void chrome.runtime.sendMessage({type:'CONTEXT_PAUSE'});};},[missionId,extension]);
 useEffect(()=>{if(!live)return;let pending=false;const timer=setInterval(()=>{if(pending)return;pending=true;void(async()=>{const [active]=await chrome.tabs.query({active:true,lastFocusedWindow:true});await refresh([...new Set([...selected,...(active?.id===undefined?[]:[active.id])])].slice(0,5));})().catch(e=>{setError(String(e));void pause();}).finally(()=>{pending=false;});},3000);return()=>clearInterval(timer);},[live,selected,automatic,onShared,onClear]);
 useEffect(()=>{if(!extension)return;const revoke=()=>{generation.current++;sharingAllowed.current=false;setAutomatic(false);setLive(false);setSources([]);setShot(null);void clearShared();};chrome.permissions.onRemoved.addListener(revoke);return()=>chrome.permissions.onRemoved.removeListener(revoke);},[extension]);
 useEffect(()=>{const timer=setInterval(()=>setSources(current=>current.filter(s=>s.expiresAt>Date.now())),1000);return()=>clearInterval(timer);},[]);
 function chooseTabs(){// Request synchronously inside the user gesture.
  void chrome.permissions.request({permissions:['tabs']}).then(async granted=>{if(!granted)throw new Error('Tab metadata permission was declined.');setTabs((await chrome.tabs.query({})).filter(t=>!t.incognito&&t.id!==undefined&&/^https?:/.test(t.url||'')));}).catch(e=>setError(String(e)));
 }
 function start(continuous=true){const epoch=++generation.current;void clearShared();const origins=[...new Set(tabs.filter(t=>selected.includes(t.id!)).map(t=>new URL(t.url!).origin))];if(!origins.length){setError('Choose one to five tabs first.');return;}
  void chrome.permissions.request({origins:origins.map(o=>o+'/*')}).then(async granted=>{if(!granted)throw new Error('Page access declined.');if(epoch!==generation.current)return;await chrome.runtime.sendMessage({type:'CONTEXT_START',missionId,tabIds:selected,sites:origins}).then(r=>{if(r.error)throw new Error(r.error);});if(epoch!==generation.current)return;setSites(origins);await refresh(selected,continuous);if(!continuous)await chrome.runtime.sendMessage({type:'CONTEXT_PAUSE'});}).catch(e=>setError(String(e)));
 }
 if(!extension)return <Notice>Selected tabs and Live Assist are available in the installed extension. Manual evidence works in this preview.</Notice>;
 return <section className="evidence-panel" aria-label="Browser context" style={{paddingBlock:12}}>
 <div className="row-between"><p role="status" className="small" style={{margin:0}}>Live Assist: {live?(automatic?'On · sharing authorized':'On · local only'):'Paused'} · {sources.length} sources</p><Button variant="secondary" onClick={()=>void pause()} disabled={!live&&!sources.length}>Pause & clear</Button></div>
 <p className="small muted" style={{margin:'4px 0',overflowWrap:'anywhere'}}>Source: {sources.at(-1)?.title||'None'} · Last update: {sources.length?new Date(Math.max(...sources.map(s=>Date.parse(s.capturedAt)))).toLocaleTimeString():'Not captured'}</p>
 {error&&<Notice tone="amber">{error}</Notice>}
 <details><summary>Manage sources, privacy & screenshots</summary><p className="small muted">Choose up to five sources. Picker titles and URLs stay on this device.</p>
 <Button variant="secondary" onClick={chooseTabs}>Choose tabs</Button>
 {tabs.length>0&&<fieldset><legend>Selected-tab research</legend>{tabs.map(t=><label key={t.id} style={{display:'block',overflowWrap:'anywhere'}}><input type="checkbox" checked={selected.includes(t.id!)} disabled={live||(!selected.includes(t.id!)&&selected.length>=5)} onChange={e=>setSelected(e.target.checked?[...selected,t.id!]:selected.filter(id=>id!==t.id))}/>{t.title||new URL(t.url!).origin}{t.discarded?' · unavailable (discarded)':''}<small> · {new URL(t.url!).origin}</small></label>)}</fieldset>}
 <p className="small muted">Live Assist extracts selected sources and the foreground page on the exact sites below for ten minutes while this panel is open. The total source limit is five; with five selected tabs, only those tabs are collected. It checks for changes every three seconds and keeps only the latest local snapshot. Automatic sharing is off by default. If enabled below, changed text goes to this mission’s backend and configured conversation model provider (including Amazon Bedrock when selected); it does not invoke the model on every update. Review a snapshot to save and send it as mission evidence. Saving evidence retains it on the backend and may share it with your configured model provider. Pause clears temporary context; previously sent evidence cannot be recalled.</p>
 {onShared&&<label><input type="checkbox" checked={automatic} onChange={e=>{generation.current++;sharingAllowed.current=e.target.checked;setAutomatic(e.target.checked);if(!e.target.checked)void clearShared();}}/>Allow automatic sharing of extracted text with this mission’s backend and configured model provider for this session (temporary backend context expires after ten minutes; provider retention is outside MissionDeck).</label>}
 <p className="small">Sites: {[...new Set(tabs.filter(t=>selected.includes(t.id!)).map(t=>new URL(t.url!).origin))].join(', ')||'None selected'}</p>
 <div className="header-actions"><Button variant="secondary" onClick={()=>start(false)} disabled={live||!selected.length}>Capture selected once</Button><Button onClick={()=>start(true)} disabled={live||!selected.length}>Allow sites & start Live Assist</Button><Button variant="secondary" onClick={()=>void refresh().catch(e=>setError(String(e)))} disabled={!live}>Refresh selected tabs</Button></div>
 <Button variant="secondary" onClick={()=>void pause().then(()=>chrome.permissions.remove({origins:sites.map(s=>s+'/*')})).then(()=>setSites([]))}>Manage sites: revoke access</Button>
 <details><summary>Inspect context ({sources.length})</summary>{sources.map(s=><article key={s.snapshotId} className="evidence-row"><h3>{s.title}</h3><p className="small">{s.sourceUrl} · {new Date(s.capturedAt).toLocaleTimeString()} · {s.completeness}{s.truncated?' · truncated':''}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:240,overflow:'auto'}}>{s.text}</pre>{s.blocks?.filter(b=>b.kind==='table').map((b,i)=><table key={i}><caption>Extracted table · blank cells remain unknown</caption><tbody>{b.rows?.map((row,j)=><tr key={j}>{row.map((cell,k)=>{const header=b.headers?.find(h=>h.row===j&&h.column===k);return header?<th key={k} scope={header.scope}>{cell}</th>:<td key={k}>{cell}</td>;})}</tr>)}</tbody></table>)}<Button onClick={()=>onReview(s)}>Review to save & share</Button></article>)}</details>
 <Button variant="secondary" onClick={()=>void chrome.runtime.sendMessage({type:'CONTEXT_SCREENSHOT'}).then(r=>{if(r.error)throw new Error(r.error);setShot(r.image);setShotSource(r.sourceUrl);}).catch(e=>setError(String(e)))}>Preview screenshot of foreground tab</Button>
 {shot&&<div><p>Screenshot preview · {shotSource}. Local only; no image sharing or vision inference is implemented. Live Assist never captures images. Use Discard if private content is visible.</p><label><input type="checkbox" checked={redaction} onChange={e=>setRedaction(e.target.checked)}/>Redact: click image to paint a black rectangle (100 × 40 display pixels)</label><img ref={shotImage} onClick={redactShot} onLoad={e=>setCrop({x:0,y:0,width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})} src={shot} alt="Explicitly requested visible tab screenshot" style={{maxWidth:'100%'}}/><fieldset><legend>Crop screenshot (image pixels)</legend>{(['x','y','width','height'] as const).map(field=><label key={field} style={{display:'inline-block',marginRight:8}}>{field}<input aria-label={`Crop ${field}`} type="number" min={field==='x'||field==='y'?0:1} step={1} value={crop[field]} onChange={e=>setCrop({...crop,[field]:Number(e.target.value)})} style={{width:75,display:'block'}}/></label>)}<Button variant="secondary" onClick={cropShot}>Apply crop</Button></fieldset><Button variant="secondary" onClick={()=>{if(!shotImage.current)return;const canvas=document.createElement('canvas');canvas.width=shotImage.current.naturalWidth;canvas.height=shotImage.current.naturalHeight;const ctx=canvas.getContext('2d');if(ctx){ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);setShot(canvas.toDataURL('image/png'));}}}>Redact entire screenshot</Button><Button variant="secondary" onClick={()=>setShot(null)}>Discard screenshot</Button></div>}
 </details></section>;
}
