import {afterEach,describe,it,expect,vi} from 'vitest';
import {captureAuthorizedTab,installBrowserContext} from './browser-context';
const tab={id:1,windowId:1,active:true,url:'https://example.com/',title:'api_key=do-not-copy-raw-title',incognito:false,discarded:false};
function mock(){const c={tabs:{get:vi.fn().mockResolvedValue(tab),query:vi.fn().mockResolvedValue([tab]),onUpdated:{addListener:vi.fn()},onRemoved:{addListener:vi.fn()},captureVisibleTab:vi.fn().mockResolvedValue('data:image/png;base64,image')},windows:{get:vi.fn().mockResolvedValue({focused:true})},permissions:{onRemoved:{addListener:vi.fn()},contains:vi.fn().mockResolvedValue(true)},runtime:{id:'extension',getURL:(s:string)=>'chrome-extension://extension/'+s,onMessage:{addListener:vi.fn()}},scripting:{executeScript:vi.fn().mockResolvedValue([{documentId:'trusted-document',result:{text:'Public',title:'api_key=[REDACTED]',sourceUrl:'https://attacker.test/',method:'page',truncated:false,blocks:[],completeness:'readable'}}])}};vi.stubGlobal('chrome',c);return c;}
afterEach(()=>vi.unstubAllGlobals());
describe('browser identity boundary',()=>{
 it('uses Chrome source identity while retaining the extractor redaction for titles',async()=>{mock();const s=await captureAuthorizedTab(1);expect(s.sourceUrl).toBe(tab.url);expect(s.title).toBe('api_key=[REDACTED]');expect(s.documentId).toBe('trusted-document');});
 it('drops delayed captures from a prior navigation',async()=>{const c=mock();c.tabs.get.mockResolvedValueOnce(tab).mockResolvedValueOnce({...tab,url:'https://other.example/'});await expect(captureAuthorizedTab(1)).rejects.toThrow('Source changed');});
 it('does not reactivate discarded or capture incognito tabs',async()=>{const c=mock();c.tabs.get.mockResolvedValue({...tab,discarded:true});await expect(captureAuthorizedTab(1)).rejects.toThrow('Unavailable');expect(c.scripting.executeScript).not.toHaveBeenCalled();c.tabs.get.mockResolvedValue({...tab,incognito:true});await expect(captureAuthorizedTab(1)).rejects.toThrow('Unavailable');});
 it('rejects page senders and malformed extension commands',()=>{const c=mock();installBrowserContext();const handler=c.runtime.onMessage.addListener.mock.calls[0]![0];expect(handler({type:'CONTEXT_PAUSE'},{id:'extension',url:'https://example.com'},vi.fn())).toBe(false);expect(handler({type:'CONTEXT_START',missionId:'m',tabIds:[1],sites:['https://example.com'],execute:'arbitrary'},{id:'extension',url:'chrome-extension://extension/index.html'},vi.fn())).toBe(false);});
 it('discards screenshots when another window becomes foreground',async()=>{const c=mock();c.windows.get.mockResolvedValue({focused:false});installBrowserContext();const handler=c.runtime.onMessage.addListener.mock.calls[0]![0];const response=await new Promise<any>(resolve=>handler({type:'CONTEXT_SCREENSHOT'},{id:'extension',url:'chrome-extension://extension/index.html'},resolve));expect(response.image).toBeUndefined();expect(response.error).toContain('Visible tab changed');});
});

it('detects changed table relationships even when visible text is unchanged',async()=>{const c=mock();const first=await captureAuthorizedTab(1);c.scripting.executeScript.mockResolvedValue([{documentId:'trusted-document',result:{text:'Public',title:'Redacted',sourceUrl:'https://example.com/',method:'page',truncated:false,blocks:[{kind:'table',text:'Public',rows:[['Public']],headers:[{row:0,column:0,scope:'col'}]}],completeness:'readable'}}] as never);const next=await captureAuthorizedTab(1);expect(next.text).toBe(first.text);expect(next.contentHash).not.toBe(first.contentHash);});
