import {describe,it,expect} from 'vitest';
import {ContextSessionManager,type ContextSnapshot} from './context-session';
function sample(m:ContextSessionManager,tabId=1):ContextSnapshot{return {snapshotId:'snap',sessionId:m.sessionId,missionId:'m',tabId,windowId:1,documentId:'d',navigationEpoch:0,permissionEpoch:m.permissionEpoch,text:'hello',title:'Page',sourceUrl:'https://example.com/',capturedAt:new Date().toISOString(),expiresAt:Date.now()+10000,method:'page',truncated:false,contentHash:'a'.repeat(64)};}
describe('context consent and stale response boundary',()=>{
 it('rejects unselected background sources, accepts foreground within exact scope',()=>{const m=new ContextSessionManager();m.start('m',[1],['https://example.com']);expect(m.accept(sample(m,2),false)).toBe(false);expect(m.accept(sample(m,2),true)).toBe(true);expect(m.accept({...sample(m),sourceUrl:'https://other.example/'},true)).toBe(false);});
 it('drops navigation and permission races',()=>{const m=new ContextSessionManager();m.start('m',[1],['https://example.com']);const s=sample(m);m.navigate(1);expect(m.accept(s,false)).toBe(false);m.pause();expect(m.accept(s,false)).toBe(false);expect(m.snapshots.size).toBe(0);});
 it('expires and does not resume after restart',()=>{const m=new ContextSessionManager();m.start('m',[1],['https://example.com'],0);expect(m.allowed(1,'https://example.com',true,600001)).toBe(false);expect(new ContextSessionManager().paused).toBe(true);});
 it('freezes content without local IDs and deduplicates updates',()=>{const m=new ContextSessionManager();m.start('m',[1],['https://example.com']);expect(m.accept(sample(m),false)).toBe(true);expect(m.accept(sample(m),false)).toBe(false);const frozen=m.freeze('req');m.accept({...sample(m),text:'changed',contentHash:'b'.repeat(64)},false);expect(frozen.sources[0]?.text).toBe('hello');expect(frozen.sources[0]).not.toHaveProperty('tabId');});
 it('isolates mission switches and bounds request text',()=>{const m=new ContextSessionManager();m.start('m',[1,2,3],['https://example.com']);for(const id of [1,2,3])m.accept({...sample(m,id),text:'x'.repeat(20000)},false);expect(m.freeze('req').sources.reduce((n,s)=>n+s.text.length,0)).toBe(50000);m.start('other',[1],['https://example.com']);expect(m.accept(sample(m),false)).toBe(false);expect(m.snapshots.size).toBe(0);});
});

it('renews session identity after pause, rejecting delayed prior-session responses',()=>{const m=new ContextSessionManager();m.start('m',[1],['https://example.com']);const old=sample(m);const id=m.sessionId;m.pause();m.start('m',[1],['https://example.com']);expect(m.sessionId).not.toBe(id);expect(m.accept(old,false)).toBe(false);});
it('does not accumulate unrelated prior foreground tabs in shared context',()=>{const m=new ContextSessionManager();m.start('m',[1],['https://example.com']);m.accept(sample(m),false);m.accept(sample(m,2),true);m.accept(sample(m,3),true);expect([...m.snapshots.keys()]).toEqual([1,3]);});
it('freezes literal table relationships and source citations within the page budget',()=>{const m=new ContextSessionManager();m.start('m',[1],['https://example.com']);m.accept({...sample(m),blocks:[{kind:'table',text:'Name\nState\nLaunch\nUnknown',rows:[['Name','State'],['Launch','Unknown']],headers:[{row:0,column:0,scope:'col'}]}]},false);const source=m.freeze('table-request').sources[0]!;expect(source.text).toContain('"rows":[["Name","State"],["Launch","Unknown"]]');expect(source.text).toContain('"scope":"col"');expect(source.sourceUrl).toBe('https://example.com/');expect(source.snapshotId).toBe('snap');expect(source.text.length).toBeLessThanOrEqual(20000);});
